### PR TITLE
Ignore dist files

### LINKED ISSUE #218: Workflow for managing dist files
# Description
Currently dist file are not in gitignore and hence huge lines of change needs to be merged in each PR. This leads to conflicts in dist files in other PR's etc. Dist files workflow are not very clear to a  new comers and they usually get stuck with the grunt build step.

# Solution
We can add dist to .gitignore
This has been done in IS repo here https://github.com/publiclab/image-sequencer/pull/908

cc @sagarpreet-chadha @jywarren

### PR DESCRIPTION
**Pull request by ananyaarun**
Fixes #218 

based on IS pr https://github.com/publiclab/image-sequencer/pull/908

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by ananyaarun** [comment]
@jywarren @sagarpreet-chadha as discussed in the call I have added dist to gitignore.

**Comment by sagarpreet-chadha** [comment]
Oh cool! Sorry i missed the call .
So how do we plan to 'grunt build' the dist ? 
Will the maintainer do that before releasing new version ? Thanks!

**Comment by ananyaarun** [comment]
According to me a developer can grunt build the dist files to run and test their changes locally (this has been added to readme)
And as you said perhaps the maintainer can do that before releasing a new version ?

**Comment by sagarpreet-chadha** [comment]
Okay great! @jywarren can we automate grunt build process prior to npm publish ?

**Comment by jywarren** [comment]
I think it is possible. I put some notes here?
https://github.com/publiclab/image-sequencer/issues/773#issuecomment-504712022

**Pull request merged**
