### PR TITLE
categorization of some layers done

### LINKED ISSUE #188: Categorize leaflet environmental layers based on type
## Description 
Currently there are too many layers in LEL menu and it needs organization

## Solution
Heading can be added using simple html tags to create a menu like this 

lel2

### PR DESCRIPTION
**Pull request by ananyaarun**
Fixes #188 

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

lel3

Thanks!

### CODE REVIEW

**Comment by ananyaarun** [comment]
@sagarpreet-chadha @jywarren  This can be a temporary fix for users to better understand the layer types.
In the long run are we planning to integrate the static html page developed ?

**Comment by jywarren** [comment]
The static html menu will be one of several ways to interact with layer
toggling. The existing menu should still be maintained too!

**Comment by ananyaarun** [comment]
@jywarren , how does this look ?

**Comment by jywarren** [comment]
This looks great!

**Comment by jywarren** [comment]
Ready to merge?

**Comment by ananyaarun** [comment]
Yes @jywarren :) Thanks for the review !!

**Pull request merged**
