### PR TITLE
Display new items mark in layers menu

### LINKED ISSUE #133: Display "new items" mark in Layers menu when you enter an area with a new layer
Some layers are really concentrated on only one region, and we have a proposal to display those layers only when you're with in the bounding box for that layer. 

This will take some work -- #117 -- but once it's complete, we could actually alert users that there is new information to display by showing either a red dot or a small number (like the "new emails" dot on some phones) which calls your attention to the new layers:

image

There are multiple places we could highlight the new layers, but we might show them in a group at the top of the layers menu here:

image

We might also show them in #59's larger layer browser. 

This can't be worked on until #117 but saving it for later!

### PR DESCRIPTION
**Pull request by crisner**
Fixes #133  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by crisner** [comment]
The badge shows the number of new layers available for the user to access when the user enters specific bounds or zoom in the map view. It also reduces the number displayed when the user moves out of it without checking the layers menu. The badge becomes hidden when the user has checked the layers menu or the user is no longer in the map view of the new layers.

I checked the badge on smaller devices and it seems to be responsive. 

The number shows the number of layers without grouping them. For example, Justicemap layer group has 9 layers. I was wondering if I should just count the group instead of separate layers in the group. I would like some inputs on this.

**Comment by crisner** [comment]
I will add a gif soon. Looks like the one I just recorded is too large.

**Comment by crisner** [comment]
newmarker

**Comment by crisner** [comment]
iPhone 6_7_8 Plus

**Comment by jywarren** [comment]
This is really great! 

> if I should just count the group instead of separate layers in the group. I would like some inputs on this.

I think the full # is ok!

**Comment by jywarren** [comment]
Great, is this ready to merge? Thank you!!!

**Comment by crisner** [comment]
Yes :)

**Pull request merged**
