### PR TITLE
Test layers browser with grunt jasmine

### LINKED ISSUE #327: Write tests for custom layer control

### PR DESCRIPTION
**Pull request by crisner**
Fixes #327  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by crisner** [comment]
@jywarren, @sagarpreet-chadha, could you help me figure out why tests are failing in travis? Am I doing something wrong in travis.yml or am I not registering the tasks as I should in gruntfile? When I run `grunt babel` and then `grunt jasmine` locally everything works fine.

travis-ci org_crisner_leaflet-environmental-layers_utm_medium=notification utm_source=email

**Comment by crisner** [comment]
@jywarren, updated node version did the trick! 🎉

**Comment by jywarren** [comment]
Oh, that's awesome!!! Super! 

Is this ready for merge then?

**Comment by crisner** [comment]
Not yet. I may need to write a few more tests. I'll mention the PR in the Outreachy planning issue when it is ready. Thanks!

**Comment by jywarren** [comment]
ok, awesome! Great work!

**Comment by crisner** [comment]
@jywarren, this PR is ready for merge. :)

**Comment by jywarren** [comment]
Awesome!!!!

**Comment by sagarpreet-chadha** [comment]
This is Awesome!!!

**Pull request merged**
