### PR TITLE
Update source of truth of layers in AllLayers.js

### PR DESCRIPTION
**Pull request by daemon1024**
Ref #528 

This will help support spreadsheet layers in oneLinerCodeExample.html once added to info.json

### CODE REVIEW

**Comment by daemon1024** [comment]
Will need to fix #553 before we can actually verify this script

**Comment by daemon1024** [comment]
why would it fail 🤔 seemed to work fine. Will have to debug the tests!

**Review by jywarren — APPROVED** [review]

**Comment by jywarren** [comment]
I like the execution though! Good work!

**Comment by jywarren** [comment]
Looks like a couple bad refs while accessing arrays:

```
   - baselayer is added by default......X
     TypeError: undefined is not a function (evaluating 'window['L']['layerGroup'][layer]()') in file:///home/runner/work/leaflet-   - embed shows embed control......X
     TypeError: undefined is not a constructor (evaluating 'window['L']['layerGroup'][layer]()') in file:///home/runner/work/leaflet-environmental-layers/leaflet-environmental-layers/dist/LeafletEnvironmentalLayers_babel.js (line 5135) (1)
```

**Comment by daemon1024** [comment]
Seems like, if there's no "include" in options, it's erroring out at https://github.com/publiclab/leaflet-environmental-layers/blob/3596bbb3f0995f2246a9cd56728f74ccdee0c855/src/AllLayers.js#L106

Probably some issue with https://github.com/publiclab/leaflet-environmental-layers/blob/3596bbb3f0995f2246a9cd56728f74ccdee0c855/src/AllLayers.js#L54-L57

**Comment by daemon1024** [comment]
Seems like `purpleair` is causing issue and giving out this particular error. Looking into it.

**Comment by daemon1024** [comment]
Ohh purpleair is actually a superset of purplelayer and purpleairmarker, so it wouldn't fit in here.

**Comment by daemon1024** [comment]
🥳

**Comment by jywarren** [comment]
nice!!!

**Pull request merged**
