### PR TITLE
Upgrade Unearthing PVD layer to latest dataset (GeoJSON)

### PR DESCRIPTION
**Pull request by gabrielrumiranda**
I make this PR for issue #292 
Screen Shot 2019-12-06 at 15 01 51

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by gabrielrumiranda** [comment]
In PR description I put a screenshot of popup

**Comment by jywarren** [comment]
This is wonderful!!! Thanks so much! 

I have a couple small requests - could we just display `sic_title` in an `<h4>` or even `<p><b>...</b></p>` just because it will read more easily as the title that way? 

Also, wanted to know -- if a datapoint has no "conames" property, for example, will it fail gracefully? What would it show? 

Thank you!!!!

**Comment by sagarpreet-chadha** [comment]
Awesome 😄 !!! Just a small change above and this is ready to be merged.

**Comment by gabrielrumiranda** [comment]
done ! @jywarren @sagarpreet-chadha

**Comment by jywarren** [comment]
🎉 !!!! Thank you so much!

**Comment by jywarren** [comment]
Would you have any interest in this related issue? https://github.com/publiclab/leaflet-environmental-layers/issues/288

**Pull request merged**
