### PR TITLE
Github Action to generate spreadsheet layers

### PR DESCRIPTION
**Pull request by daemon1024**
Ref #528 https://github.com/publiclab/plots2/issues/9698

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by daemon1024** [comment]
Noting some additional tasks for future PRs

https://github.com/daemon1024/leaflet-environmental-layers/issues/10#issuecomment-874816721

**Comment by daemon1024** [comment]
@github-actions run
```json
{
"name":"Action Test",
"url":"check"
}
```

**Comment by jywarren** [comment]
This before https://github.com/publiclab/leaflet-environmental-layers/pull/549

**Comment by jywarren** [comment]
Love it!!

**Pull request merged**
