### PR TITLE
Added SEO meta tags and made some changes in README.

### PR DESCRIPTION
**Pull request by sidntrivedi012**
@jywarren @sagarpreet-chadha @gauravano Please review.

### CODE REVIEW

**Comment by jywarren** [comment]
This is great, thank you! Can you share a screenshot so we can just double check that it all renders correctly? Thanks!

**Comment by sidntrivedi012** [comment]
@jywarren Do I have to add the screenshot of my local project or the social media cards (SEO feature) that are formed when one enters the url of LEL?

**Comment by sidntrivedi012** [comment]
@jywarren I have resolved the conflicts. Please review again.

**Comment by sidntrivedi012** [comment]
Peek 2019-04-08 12-43

**Comment by sidntrivedi012** [comment]
Peek 2019-04-08 12-47

**Comment by sidntrivedi012** [comment]
@jywarren Added the gif. Please take a look.

**Comment by jywarren** [comment]
Great work!!!!! Awesome. Thanks a lot!!

**Comment by sagarpreet-chadha** [comment]
Hey @jywarren , @ananyaarun ! 
Umm it took me some time to find the bug but i think this PR is causing the problem . 
See line 232 - 333 and 337 - 432 .
There is repetition of same code in here . 
Also i think the `<meta>` tags should always go in the `<head>` tag but they as well as all `scripts` are put outside the `head` here .

@ananyaarun , i think this should solve your issue in #180 !

**Comment by ananyaarun** [comment]
Yes there is a bug here , head tag had actually been closed twice and opened once , and yes base layers and overlay layer variables are redefined !!
I'll try to change these and see if it works :)

**Pull request merged**
