### PR TITLE
FracTracker Layer 

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
Solves #16 🛢 .

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, this looks SUPER! I think we probably need a similar "credit" to
FracTracker; maybe this should be a standard part of the library, to show a
credit line, since we have so many sources?

Great work!

**Comment by sagarpreet-chadha** [comment]
Thanks @jywarren !

I was going to ask the same question . We should place credit line on pop-up of marker  , right ?

Like this , 
screen shot 2018-06-26 at 7 48 43 pm

**Comment by sagarpreet-chadha** [comment]
For JusticeMap Layers and OpenWeather Map layers , the credit line is at the bottom right corner .

screen shot 2018-06-26 at 8 02 35 pm
screen shot 2018-06-26 at 8 02 20 pm

**Comment by jywarren** [comment]
Yes, in the popup sounds great wherever there are popups. Perhaps as we
build out a UI to better explain the different layers (and as the layers
dropdown gets too full) we can think about how to make this more
explanatory. Great!

**Pull request merged**
