### PR TITLE
Refactored code in index.html file

### LINKED ISSUE #209: Separate html css and JS code in index.html
## Description 
Currently the index.html file has all html css and js code together in one place.
This makes the file too big and hard to understand.
Like the other leaflet plugins , we can separate the js code in another file.

### PR DESCRIPTION
**Pull request by ananyaarun**
Fixes #209 

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by ananyaarun** [comment]
@sagarpreet-chadha , Do you think it is a good idea to separate css and html too ? like create a separate css file ? Let me know i'll make the required changes.
Thanks !

**Comment by sagarpreet-chadha** [comment]
Hey, Yes we can do that...how about making FTO issue for that ? Thanks 😄 !

**Comment by ananyaarun** [comment]
Sure @sagarpreet-chadha :)
So this PR separates html and css in one file and JS in another.
Should I close this and open an FTO to separate all 3 (html css and JS) into 3 different files or wait for this to get merged and open an FTO to separate html and css only ?

**Comment by ananyaarun** [comment]
@sagarpreet-chadha let me know if this can be merged and then I can open a FTO issue for html and css segregation or if I should close this.
Thanks !

**Comment by sagarpreet-chadha** [comment]
Hi @ananyaarun , there are some conflicts in this PR . We can merge this after you update the PR . Thank you :smile: !

**Comment by ananyaarun** [comment]
@sagarpreet-chadha , I have resolved the conflicts.
I'll open an FTO once this gets merged :)

**Comment by sagarpreet-chadha** [comment]
Awesome! Thank you !!!

**Pull request merged**
