### PR TITLE
Clone demo page with embed pointing to the actual page

### LINKED ISSUE #310: Clone demo page to embed.html so that actual embeds do not show the notice

### PR DESCRIPTION
**Pull request by crisner**
Fixes #310  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by crisner** [comment]
- Cloned index.html to embed.html
- Removed notice from showing in index.html
- Added notice to appear only on embed.html
- Embed code in embed.html points to `//publiclab.github.io/leaflet-environmental-layers/example/index.html`

##### Screenshot of embed page with embed code:
embed-demo

**Comment by crisner** [comment]
@jywarren, could you take a look at this to see if I got this right?

**Comment by jywarren** [comment]
Looks perfect!

**Comment by jywarren** [comment]
Thanks a ton!!!!!

**Comment by crisner** [comment]
🎉 😃

**Comment by sagarpreet-chadha** [comment]
Awesome!!!

**Pull request merged**
