### PR TITLE
Testing index page

### LINKED ISSUE #398: Write tests for LEL demo index page
Adding tests for the demo index page from the examples.

### PR DESCRIPTION
**Pull request by crisner**
Fixes #398 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by crisner** [comment]
Have added tests to check the UI of the demo index page. I am still trying to figure out how to get the hashing library to work within the test browser. 
image

**Comment by crisner** [comment]
Got it to work using the hash library! 🎉 
image

**Comment by crisner** [comment]
I've run into another issue while trying to assert if the hash changes on map movement. The hash seems to affect the cypress iframe and I am getting a test window within a test window.

image

@sagarpreet-chadha, do you have any idea why this is happening?

**Comment by crisner** [comment]
This tests the UI elements in the demo page except adding layers.
image

**Comment by crisner** [comment]
The tests are passing but I've caught another issue. The first time I open cypress and run tests they fail because the tests run before our page is fully loaded. Cypress seems to have a better way than just adding a wait time. I am looking it so that our tests start only when our page is ready.

**Comment by crisner** [comment]
Tried the workarounds but Cypress would time out after 4 seconds. So I moved the test that tests the hash update to a separate file and increased wait times after each URL update. The need for the delay may be only for my machine but added it in to be safe.

**Comment by crisner** [comment]
image

**Comment by nstjean** [comment]
Oh this looks so cool! I bet we have better luck testing the presence of layers using this.

**Comment by nstjean** [comment]
I also noticed that you can run it from the command `npx cypress run -b chrome`. Are we going to add this test to the automatic tests that travis runs?

**Comment by crisner** [comment]
Thanks for checking it out @nstjean! I am glad to know it works. I am looking into integrating these tests with Travis so that they run automatically along with the other tests we have.

**Comment by crisner** [comment]
Well, this is frustrating. The tests are failing in headless mode because LEL is not fully loaded when the tests start to run. Increasing wait time worked when testing with a browser but it does not seem to work in headless mode. 😞

**Comment by crisner** [comment]
Looks like the workaround of using a child window so that our tests don't break Cypress's iframe does not work in headless mode. It doesn't seem to detect the DOM elements no matter how long I increase the load time.
timeout

I went back to using `cy.visit` instead of a child window and the tests pass. I see the same error I got when I tested it in Chrome where the page tries to reload and breaks out of the test frame.
image
image

The url is messed up from our app breaking out of the test iframe.
image

**Comment by crisner** [comment]
The error just causes the hash change test to fail in Travis. I am considering either removing or disabling the tests checking for hash change.
image

**Comment by crisner** [comment]
I am checking if I can run the tests in chrome browser in travis

**Comment by crisner** [comment]
It works! :tada:
I am happy we can keep the tests as it is!

**Comment by crisner** [comment]
The tests in this PR along with changes done for it to run in Travis are in PR #403 ready to be reviewed and merged.

**Comment by nstjean** [comment]
Oh yay, you got it to work in Travis!! That's excellent!

**Pull request merged**
