### PR TITLE
Sea level rise data

### PR DESCRIPTION
**Pull request by neelesh17**
Uploaded a file containing the data for sea level rise layer in LEL. @sagarpreet-chadha could you  host it on publiclab.

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
Can you put this file inside some existing data folder if any or create a new one. Thank!

**Comment by neelesh17** [comment]
@sagarpreet-chadha Done.

**Comment by neelesh17** [comment]
> Can you put this file inside some existing data folder if any or create a new one. Thank!

@sagarpreet-chadha I have made the  changes you requested.

**Comment by sagarpreet-chadha** [comment]
Hey @neelesh17 ,done 👍 
Sorry for late response 😄

**Comment by neelesh17** [comment]
@sagarpreet-chadha what would be the url to access the data.

**Pull request merged**
