### PR TITLE
Mapknitter marker changed

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
@jywarren ...how does this look ?

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
screen shot 2018-07-12 at 11 33 19 pm

**Comment by sagarpreet-chadha** [comment]
Kind of stuck here...trying to use https://github.com/lvoogdt/Leaflet.awesome-markers but not working yet ,
trying to resolve again !

**Comment by sagarpreet-chadha** [comment]
Hi @jywarren !
I ended up using https://github.com/pointhi/leaflet-color-markers from the list provided by you above , 
How does this looks ? 
screen shot 2018-07-17 at 10 25 48 pm

**Comment by sagarpreet-chadha** [comment]
Moved to PR #34 !

**Comment by jywarren** [comment]
ooh this looks great!

**Pull request closed without merging**
