### PR TITLE
Added a prototype for aqicnLayer and tileLayer

### LINKED ISSUE #49: Air quality layer via aqicn.org
http://aqicn.org/here/ has some great data, but also their break-out page for each station is really good:

http://aqicn.org/city/usa/rhode-island/near-road/

image

### PR DESCRIPTION
**Pull request by kevinzluo**
Fixes #49 and #57 

I have begun to implement the AQI Layer. Luckily there is no CORS blocked error this time!

The first of the AQI layers (waqiLayer) is a tileLayer provided by AQICN. The issue with it is that it does not provide any more specific information, such as the city name.

The second of the layers (AQICNLayer) is one I am trying to build. 
Currently I first grab data for stations within a region, which provides only their AQI, lat, lng, and uid. Then for each station in the region I grab more specific data using their ID (which for some reason changes to being called idx in their API?). The specific data includes measurements beyond the AQI, such as ozone measurements. 
The problem with this is that there is a 1000 query per minute quota on each token ID, and because there are so many stations, the quota is quickly reached, even though I have tried to adjust the hashMap to only call for new stations.

Features to implement:
- [X] Use widget API to create popups. This might eliminate the need to request more specific station data, but it also counts in the quota.
- [X] Change marker color based on AQI. AQICN defines several different levels. Currently all markers are the default.
- [X] Possibly set a min and max zoom

Current Issues:
- [ ] Quota is reached very quickly
- [ ] Map lags very badly due to too many markers

### CODE REVIEW

**Comment by kevinzluo** [comment]
@jywarren @sagarpreet-chadha 
Could you please give me some advise on how to fix these issues?

**Comment by sagarpreet-chadha** [comment]
AWESOME WORK 🎉 👍 😃 ! 

Adding some links first for other reviewers to see the documentations : 
1.) http://aqicn.org/json-api/doc/   => API documentation .
2.) http://aqicn.org/faq/2015-07-28/air-quality-widget-new-improved-feed/   => widget API 


The API limit is **1000 requests per minute**  so we are good to go for now 👍 !

Also you have used this table for color coding : 
screenshot 2018-11-08 at 11 25 35 am

**Comment by sagarpreet-chadha** [comment]
@jywarren 
Because the data is very large we can even use a map-tile-layer to show data , but we will not be able to use WIDGET API (that shows the pop-up) , but using this will ensure that the map does not lag .

Map-tile-layer on leaflet works smoothly : 
screenshot 2018-11-08 at 11 44 56 am


What do you think @kevinzluo ?

**Comment by kevinzluo** [comment]
Yep. I also saw the map tile layer and implemented it in my first commit before removing it. I created the other layer to add the popups and additional info.

The layer I created does not lag too badly unless at low zoom levels, and I changed it to only fetch station specific data on popup open so the quota is not an issue.

I am fine with whichever we choose to use. Would you like me to re add the tileLayer?

**Comment by kevinzluo** [comment]
Hi. This one has been rebased too.

**Comment by jywarren** [comment]
This is /fantastic/ -- really tremendous work. 

I'm going to bump the version number in `package.json` so these get picked up in MapKnitter and PublicLab.org next time they build. In the future, for any new feature, you can do the same and include it in the PR! See https://semver.org for more details.

**Pull request merged**
