### PR TITLE
mapknitter marker pop up changed

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
screen shot 2018-07-19 at 12 39 27 pm

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
Author added in pop-up .

**Comment by sagarpreet-chadha** [comment]
Hi @jywarren !
If this is fine ...then merge this PR before merging https://github.com/publiclab/mapknitter/pull/270 .
Thanks 🚦 .

**Comment by jywarren** [comment]
This is great! A few more small tweaks:

1. can we make lat/lon on the same line, to save space?
2. could clicking on the title open the map page, and clicking on the username open the user profile on PublicLab.org?

**Comment by sagarpreet-chadha** [comment]
Hi @jywarren 
Kindly review the changes 😄 .

screen shot 2018-07-28 at 11 31 08 am

**Comment by sagarpreet-chadha** [comment]
Should we do a version bump before integrating to plots2 AND mapknitter 🤔  ?

**Comment by jywarren** [comment]
Yes, let's do - although if bower.json is set right, a patch-level bump of 0.0.x would get picked up by both... shall i merge this? Looks AWESOME!!!

**Comment by sagarpreet-chadha** [comment]
Yes lets merge this .

**Comment by jywarren** [comment]
Maybe we should just add a feature to Leaflet Env Layers to override the markers, so it's easier to make it compatible with existing map icon conventions? Or, we could make LEL's markers all half-sized because they're generally going to be "extra"?

**Comment by sagarpreet-chadha** [comment]
Okay 👍 ! 
I guess i will do both , first making size of extra markers smaller  and making follow up issue to over-ride size of markers . 

@jywarren ...lets merge this then 😄 !

**Pull request merged**
