### PR TITLE
Collect layer information

### LINKED ISSUE #316: Collect layer information to be displayed in the layers browser menu

### PR DESCRIPTION
**Pull request by crisner**
Fixes #316  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by crisner** [comment]
@jywarren, I have collected the information for all layers and have added a short text in `layer_desc` to be displayed under each layer. 

One of the layers had mentioned 'near real-time' data and some others mentioned 'real-time' or 'current' data. Is it okay to classify them all under 'near real-time'? We could display these layers as `NRT` or as `NRT/RT` as shown in the screenshot below.

For data validity and reliability, we could add an exclamation icon for each layer which would open up a modal containing information about the data. The text under disclaimer in the JSON file would go in the modal.

##### Mockup:
menu

**Comment by crisner** [comment]
I had also looked for links for reporting information for layers that accept community submissions. Only the odorreport layer had a link that directly pointed to a form. Opensense and Purpleair layers accept sensor data but one has to register or sign in to do so. Pfas layer has an email where people can send in a report if a site was missing in the data provided by them.

Do I include them all in the menu so that users are directed to those pages if they want to submit a report? or do we display the report option only for odorreport layer?

**Comment by jywarren** [comment]
I like the icon! What about an (i) icon for info, instead?

And for the reporting, I think we can link to whatever the first step is in
reporting, so for PA do they have a signup page? Or even just purpleair.com?
Let's cast a wide net!

Awesome!

**Comment by crisner** [comment]
Bumped version indicating minor change.

**Comment by crisner** [comment]
> so for PA do they have a signup page?
Yes, they have a register page.

> What about an (i) icon for info, instead?
That'd be great! We could use the info circle icon from fontawesome. https://fontawesome.com/icons/info-circle?style=solid

**Comment by crisner** [comment]
Information gathered in this PR related to this Issue #138.

**Comment by crisner** [comment]
@sagarpreet-chadha, I was thinking about npm versioning in LEL and began wondering if the changes we have contribute to a major change instead of a minor one? We've changed the hashing library used and changed the location of the lib folder as well. Wouldn't this be a breaking change? Just wondering here. Please correct me if I am wrong. What are your thoughts on this?

**Comment by jywarren** [comment]
Hi! Usually the definition of breaking is if a downstream library which
depended on this one would cease to function correctly unless refactored
--- in that sense the version is a signal to them not to use this new
version until they've confirmed the refactor, or they risk their code
breaking. So, unless we change what we've "promised" in the readme, in
terms of functions, usage, etc, it shouldn't be a breaking change. Hope
this helps!!

**Comment by crisner** [comment]
@jywarren, thanks for explaining it to me! I think I get it. I may have to do a bit more reading on the topic to become comfortable with it. 😄

**Pull request merged**
