### PR TITLE
Structured and added some documentation to the code.

### PR DESCRIPTION
**Pull request by sidntrivedi012**
@jywarren @sagarpreet-chadha @gauravano Added some documentation so that newcomers can understand the code easily. Also shifted the styles under one tag . Please review.

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, thank you! Do you think you could upload a screenshot to help confirm that everything still works? Thanks!!!

**Comment by sidntrivedi012** [comment]
@jywarren Sure.

**Comment by sidntrivedi012** [comment]
Peek 2019-03-13 08-33

**Comment by jywarren** [comment]
Thank you -- actually @rkpattnaik780 do you think you could offer a review? Thanks!

**Comment by jywarren** [comment]
And, apologies, but it looks like it needs a conflict resolution -- @sidntrivedi012 would you mind? Thanks a lot, I really appreciate it, this library is slowly coming together! Maybe we should promote it a bit on the weekly Community Check-in! https://github.com/publiclab/image-sequencer/issues/883

**Comment by sidntrivedi012** [comment]
@jywarren @sagarpreet-chadha @gauravano Please review. Resolved the conflicts.

**Comment by jywarren** [comment]
Thank you!!!

**Pull request merged**
