### PR TITLE
Replace layer control with new layers browser menu

### LINKED ISSUE #318: Replace leaflet layer control with new layers browser menu
Replace the existing layer control with new layers browser menu from the mockup in #232

### PR DESCRIPTION
**Pull request by crisner**
Fixes #318  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by crisner** [comment]
This is what I have so far:
layerBrowserMenu

What's left to do:
- Refactor code
- More styling on the report button
- Pull data from the layers information JSON file submitted in PR #317 
- Update style changes

**Comment by crisner** [comment]
Work done:
- Refactored code to avoid repetition
- Pulled in sample information from JSON file
- Updated styles

layerBrowserMenu_v2

Things to do:
- Update style of data info popup or add a different popup
- Pull in actual data
- Show only/filter layers available in the current bounds
- Add media queries

layerBrowserMenu_v2_dataInfoModal

**Comment by crisner** [comment]
@jywarren, @sagarpreet-chadha, please let me know what you think about what I have done so far. Also, should I wait for PR #317 to be merged or shall I copy the JSON file from it to this PR so that I can use it to pull in information?

**Comment by sagarpreet-chadha** [comment]
I have not reviewed in depth, will do after the PR is done from your side. 
This looks fantastic 😄 !!! 
I am just wondering how it will look for small maps on plots2, like profile map or side-bar map?
Also how do we close this control bar as the overlay button is not visible in screenshots.
Thanks!

**Comment by crisner** [comment]
Thanks! I shall attach a gif when I am done or apply this control to the demo file and have it live on my forked LEL repo's gh-pages if that's alright. This just replaces the default leaflet control. So, the behaviour is the same for opening and collapsing with some added features to the layers list. 😄 

> I am just wondering how it will look for small maps on plots2, like profile map or side-bar map?

I am assuming media queries can help with small embeds? We could hide layer information in small screens as well if it seems too crowded. I will have to make some changes to the overlays object in AllLayers.js file for testing in plots2. I'll work that when this is ready.

**Comment by crisner** [comment]
Work done:
- Pulled in actual data from JSON file
- Refactored code
- Added media queries

#### Screenshots of screens at different sizes
Screenshots 1440px & 1024px:
<div><span>1440px
1024px</span></div>
<br>
Screenshots 768px & 425px:

<div><span>768px
425px</span></div>
<br>
Screenshots 375px & 320px:

<div><span>375px
320px</span></div>
<br>

Things to do:

- Update style of data info popup or add a different popup
- Show only/filter layers available in the current bounds

**Comment by sagarpreet-chadha** [comment]
Looking super cool!!!

**Comment by crisner** [comment]
Work done:
- Worked on modal popup(updated styles, prevented duplicated modals for the same layer)
- Implemented layer filtering depending on layer bounds. Does this address this issue #117 ?

@sagarpreet-chadha, This PR is ready for review. However, there are a couple of bugs I'm stuck on. I can work on this depending on your feedback.

The feature is live at: https://crisner.github.io/leaflet-environmental-layers/example/index.html#lat=43.00&lon=-4.07&zoom=3&layers=Standard

The following are the bugs I came across:
1) The layer gets removed from the list only in the next map event when the layer is turned on.
I came across this issue when I implemented `map.removeLayer(layer)` if `map.hasLayer(layer)` returns true. When the map no longer intersects first the layer is removed from the map but still remains visible in the menu. The layer gets removed from the menu only in the next map movement. Do we need to remove the layer from view when it is filtered out or do we let it show in the view even when the layer is not accessible via the layers menu?

2) The filtering does not work when the map is first loaded on the page but work fine after reloading.
I can't seem to figure out the issue. I tried the `load` map event but there was no change in the issue. I can look into this further tomorrow. Currently, the map shows all layers on page load then actively filters out the layers after reload or map `moveend` events.

**Comment by nstjean** [comment]
This looks really good!!

**Comment by crisner** [comment]
Fixed all bugs! 🎉 😄 

P.S:- Currently a layer is completely removed from map view when it is filtered out in the layers menu. I've updated the [gh-pages](https://crisner.github.io/leaflet-environmental-layers/example/index.html#lat=43.00&lon=-4.07&zoom=3&layers=Standard) on my local repo to reflect the bug fixes.

**Comment by sagarpreet-chadha** [comment]
Hey @jywarren , if this looks good to you i can bump the version and release it to npm 😄 !

**Comment by sagarpreet-chadha** [comment]
I think let's merge this, if there will be any changes by @jywarren we can do that in another PR :)

**Comment by crisner** [comment]
Awesome! Thanks, @sagarpreet-chadha!

**Comment by jywarren** [comment]
This is INCREDIBLE! So great!

Congrats on a great job!

I'm wondering if we should open a new issue to collect tiny UI refinements and suggestions. It's a huge project and it'll be great to see how people use it. We also have a https://lookback.io account if you'd like to try recording some user testing to get feedback on this!

**Comment by crisner** [comment]
> I'm wondering if we should open a new issue to collect tiny UI refinements and suggestions. It's a huge project and it'll be great to see how people use it. We also have a https://lookback.io account if you'd like to try recording some user testing to get feedback on this!

That's a great idea!  https://lookback.io looks interesting! Posting the self-test link from lookback.io to PublicLab.org as a note or here as an issue would be a good idea to get users to test I think? or do we have a list of users, who would be ready for testing, to whom we could send the link to?

**Comment by jywarren** [comment]
We can reach out to the general public on Twitter, using the main PL
account... we can also make a GCI task from it, perhaps?

What would be your text prompt you'd like people to see, and what page
should they be pointed at?

Thanks!

**Comment by crisner** [comment]
Awesome! 

I am not confident about my content-writing abilities but here's some text I came up with for the prompt. The text prompt could be:

> "We have made a layers browser feature to browse and select layers with environmental data based on the location on the map. We would like your feedback to help make it better. Help us test the feature by clicking the link given below. The feature can be accessed by hovering or clicking on the button on the top-right."

Below the prompt, we could provide the lookback.io link with a screenshot of the map with an arrow pointing towards the button. Because the new layers menu is implemented only in the demo page we can share the gh-pages link to the demo page for the users to test.

**Comment by jywarren** [comment]
This is great; there are maybe 2 types of user tests we could build this
into - one could say, "try zooming into a specific city and turning on 3
layers", or we could do something more high-level and goals-driven "try
using it to compare 2 environmental issues" or something like that. I can
get one of these set up today and circulate it to staff and PL organizers
for starters?

**Comment by crisner** [comment]
Awesome!

**Comment by crisner** [comment]
Sounds good!

**Comment by jywarren** [comment]
Hi, just wondering - the gh-pages demo doesn't show all layers, and I wondered two things:

1. should we make the one-line version at https://github.com/publiclab/leaflet-environmental-layers/blob/master/example/oneLinerCodeExample.html be the default demo now, so rename it index.html and move `index.html` to something like `specific-layers.html`?
2. is it not showing all layers because we haven't enabled them all in the example? Let's make our default example show all available layers, and this seems to make the above idea even better, because then as we add layers to the .json file we won't have to update the example; they'll be included automatically!

What do you think?

**Pull request merged**
