### PR TITLE
Leaflet environmental layers #391

### LINKED ISSUE #391: Get data from bbox and populate popup data for opensense layer
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file layercode.js in the `leaflet-environmental-layers` repository. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

### Step 1:
Remove these lines:
https://github.com/publiclab/leaflet-environmental-layers/blob/84da2d162eeeb0662be3c1e3de4c01a38086bf50/src/layercode.js#L37-L65
https://github.com/publiclab/leaflet-environmental-layers/blob/84da2d162eeeb0662be3c1e3de4c01a38086bf50/src/layercode.js#L374-L382
https://github.com/publiclab/leaflet-environmental-layers/blob/84da2d162eeeb0662be3c1e3de4c01a38086bf50/src/layercode.js#L550

### Step 2:
Change this:
https://github.com/publiclab/leaflet-environmental-layers/blob/84da2d162eeeb0662be3c1e3de4c01a38086bf50/src/layercode.js#L21-L23
to:
```js
if (this.layer !== 'opensense') {
  this.requestData();
 } else if (this.layer === 'opensense' && map.getZoom() > 5) {
  this.requestData();
}
map.on('moveend', function() {
    if ((this.layer === 'opensense' && map.getZoom() > 5) || this.layer !== 'opensense') {
      this.requestData();
    }
}, this);
this._map = map;
```

### Step 3:
Change this:
https://github.com/publiclab/leaflet-environmental-layers/blob/84da2d162eeeb0662be3c1e3de4c01a38086bf50/src/layercode.js#L97-L99
to
```js
if (self.layer === 'opensense' && self._map.getZoom() > 5) {
    var bounds = self._map.getBounds();
    Layer_URL = 'https://api.opensensemap.org/boxes?full=true&bbox='+bounds._southWest.lng+','+bounds._southWest.lat+','+bounds._northEast.lng+','+bounds._northEast.lat;
 }
```

### Step 4:
Insert this:
```js
if (self.layer == 'opensense') {
    self.parseData(data);
}
```
above this line:
https://github.com/publiclab/leaflet-environmental-layers/blob/84da2d162eeeb0662be3c1e3de4c01a38086bf50/src/layercode.js#L115

### Step 5:
Change this:
https://github.com/publiclab/leaflet-environmental-layers/blob/84da2d162eeeb0662be3c1e3de4c01a38086bf50/src/layercode.js#L285
to:
`var content = this.generatePopup(data);`

and change this:
https://github.com/publiclab/leaflet-environmental-layers/blob/84da2d162eeeb0662be3c1e3de4c01a38086bf50/src/layercode.js#L289
to:
`return marker.bindPopup(content);`

### Step 6:
Add these lines:
```js
if (this.layer == 'opensense') {
    var popUpContent = '';
    var noMeasurements = true;
    if (item.name && item.grouptag) {
          popUpContent += '<h4>' + item.name + ',' + item.grouptag + '</h4>';
    }  else if (item.name) {
          popUpContent += '<h4>' + item.name + '</h4>';
    }

   if (item.currentLocation.coordinates) {
          popUpContent += '<span><strong>Latitude:</strong> ' + item.currentLocation.coordinates[1] + '</span><br>' + '<span><strong>Longitude:</strong> ' + item.currentLocation.coordinates[0] + '</span><br>';
   }
        
  for (var i in item.sensors) {
      if (item.sensors[i].lastMeasurement) {
            noMeasurements = false;
            popUpContent += '<span><b>' + item.sensors[i].title + ': </b>' +
              item.sensors[i].lastMeasurement.value +
              item.sensors[i].unit + '</span><br>';
       }
  }

  if (noMeasurements) {
     popUpContent += '<span><b>No measurements available</span><br>';
  }
        
  if (item.lastMeasurementAt) {
      popUpContent += '<br><small>Measured at <i>' + item.lastMeasurementAt + '</i>';
  } else if (item.updatedAt) {
      popUpContent += '<br><small>Updated at <i>' + item.updatedAt + '</i>';
  }
  return popUpContent;
}
```
right after line 332 in the `generatePopup` method:
https://github.com/publiclab/leaflet-environmental-layers/blob/84da2d162eeeb0662be3c1e3de4c01a38086bf50/src/layercode.js#L332

### Step 7:
Add the following:
```js
if (this.layer == 'opensense') {
   var marker = this.getMarker(data);
   var key;
   if (marker != null) {
      key = data._id; // ID
      if (!this._layers[key]) {
            this._layers[key] = marker;
            this.addLayer(marker);
      }
   }
}
```
right after line 353:
https://github.com/publiclab/leaflet-environmental-layers/blob/84da2d162eeeb0662be3c1e3de4c01a38086bf50/src/layercode.js#L353

### Step 8:
Change this:
https://github.com/publiclab/leaflet-environmental-layers/blob/84da2d162eeeb0662be3c1e3de4c01a38086bf50/src/layercode.js#L419
to:
`if (this.layer == 'luftdaten') {`

and add this:
```js
if (this.layer == 'opensense') {
    for (var i = 0; i < data.length; i++) {
          this.addMarker(data[i]);
    }
}
```
after line 423:
https://github.com/publiclab/leaflet-environmental-layers/blob/84da2d162eeeb0662be3c1e3de4c01a38086bf50/src/layercode.js#L423

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by robin-natale**
Fixes #391 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by crisner** [comment]
@robin-natale, are you working on this?

**Comment by robin-natale** [comment]
Hey @crisner yes! I had some trouble to set up properly the git repository on my new laptop. Later on I will push again my changes and hopefully they will be fine this time. I will send a reply as soon this is done 😉 thanks for checking in with me!!

**Comment by crisner** [comment]
Awesome! 😄

**Comment by robin-natale** [comment]
hey @crisner could you check if my changes got through properly? 👍

**Comment by crisner** [comment]
@robin-natale, sorry about this but could you close this PR and open a new one? It also looks like your branch has been removed.

**Comment by crisner** [comment]
I am closing this as you have an open PR for the same issue. Thanks!

**Pull request closed without merging**
