### PR TITLE
Static html table menu

### LINKED ISSUE #192: Static HTML mockup of the new "table" Menu in a templates folder
Referenced in https://github.com/publiclab/leaflet-environmental-layers/issues/168

I plan on completing this within the next few days

image

### PR DESCRIPTION
**Pull request by rarrunategu1**
Fixes #192  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

Still a working progress.  I have a few more things to add so it's not quite ready for review but I'm open to any suggestions based on what may be needed.  I do have a png file that is not being used but that's because I couldn't find the original for better quality.  I may delete it later.

image

### CODE REVIEW

**Comment by jywarren** [comment]
Oooooohhhhh! @ananyaarun @sagarpreet-chadha @stefannibrasil this is pretty awesome, just static HTML to build on top of -- what do you think?

**Comment by stefannibrasil** [comment]
that looks awesome!
We can potentially use it on the new front-page, it would fit really well 💅

**Comment by ananyaarun** [comment]
@rarrunategu1 this is great !!

**Comment by rarrunategu1** [comment]
Thank you.  Today I'll be putting the finishing touches on it.  I planned on it yesterday but I wasn't feeling well.  If you have any suggestions, please feel free to share them. :)

**Comment by ananyaarun** [comment]
@rarrunategu1 is there anything I can contribute to or help with this PR ?

**Comment by rarrunategu1** [comment]
@jywarren @sagarpreet-chadha @stefannibrasil @ananyaarun I've added the collapsible rows and basically just have a template ready to push.  Please take a look at it and let me know if there's anything I may have missed that you feel should be included.

**Comment by jywarren** [comment]
Thanks! Ananya, can you give it a try? If this looks good we can merge and
address any other issues in a follow-up PR!

**Comment by sagarpreet-chadha** [comment]
I love this 😍 !

@rarrunategu1 ...can we use hosted URL of the image in the code instead of adding the image in the library ? You can remove the image from this PR . 

Some follow up issues we can discuss : 

- [ ] Clicking `Add a Report` button should open a modal which has all the fields that the `POST` request of the API wants . (Will be different for different API's) . 

- [ ] Google maps also has a similar feature to add report --- we can use UI similar to that (especially in mobile view) .

- [ ] Writing AJAX call to POST report as a common function which can be used for all API's . 
One function where we pass different parameters including the URL of API , and it sends POST request to that API . 

- [ ] Integrating to projects --- mapknitter and plots2 :)

Thank you !

**Comment by ananyaarun** [comment]
I tried this out locally. It looks great!!!
Here is a working gif
static

**Comment by jywarren** [comment]
Ok! Want to offer an approving review and we can go ahead and merge it
then? Thanks!!!

**Comment by rarrunategu1** [comment]
Hello @sagarpreet-chadha, above you suggested that we use hosted URL of the image in the code instead of adding the image in the library ? Then I see an approving review.  I'm still trying to understand what all of this means.  Were the changes made or should I remove the image at the top to be able to merge this?

**Comment by sagarpreet-chadha** [comment]
Hey! 
No it seems the changes are not made . You can update the PR and then we can merge this :)
Thanks

**Comment by rarrunategu1** [comment]
I've made the changes @sagarpreet-chadha. I appreciate everyone's feedback.  It's now ready to merge @jywarren :)

**Comment by jywarren** [comment]
Awesome work, folks!

**Pull request merged**
