### PR TITLE
Add tests for embed feature

### LINKED ISSUE #313: Write tests for embed feature

### PR DESCRIPTION
**Pull request by crisner**
Fixes #313  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by crisner** [comment]
I have added some tests for the embed feature. I struggled a bit with this one as I am not used to writing tests.  Looking forward to feedback.

**Comment by crisner** [comment]
Great! I'll try breaking the tests to confirm how it reports on Travis.

**Comment by crisner** [comment]
I did as you suggested and Travis does report the errors when I push broken code. :tada: :D

**Comment by sagarpreet-chadha** [comment]
Awesome!!!

**Pull request merged**
