### PR TITLE
EWG's PFAS Layer 

### PR DESCRIPTION
**Pull request by ephemeralwaves**
Created a map layer with the PFAS data from EWG's site.

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
Hey ,
There are some conflicts in this PR with the main branch , can you kindly resolve that ? 
Also it would be great if you can share screenshot of this new layer :smile: . Thank you :tada: !

**Comment by ephemeralwaves** [comment]
Leaflet-Screenshot_2019-03-31_23-12-22
Screenshot of the PFAS layer. Not sure what the conflict is, how do I figure this out?

**Comment by sagarpreet-chadha** [comment]
Hey @ephemeralwaves ,
Great work , the Screenshot looks awesome 🎉 !
Okay so to resolve the conflicts , first you checkout to your `ephemeralwaves:master` branch . Make sure to pull latest changes from `publiclab:master` , this will cause conflicts in some file . You will have to resolve these conflicts and push the new changes back here . Makes sense ?
You can see this for more details : https://github.com/AgileVentures/MetPlus_PETS/wiki/Resolving-Pull-Request-merge-conflicts
Thanks 😄 !

**Comment by ephemeralwaves** [comment]
ok resolved the conflicts, thanks for the link!

**Comment by jywarren** [comment]
Merged this at last! Sorry it took us so long!!!!

**Pull request merged**
