### PR TITLE
[WIP] Jasmine tests for layers 

### PR DESCRIPTION
**Pull request by ananyaarun**
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by ananyaarun** [comment]
@sagarpreet-chadha @jywarren @rexagod 
I shall keep updating this PR with tests for more layers.
Plan is to at least have some basic tests for most layers in LEL repo now that we fixed the prev testing PR.

Parallely we can also work on other milestone functions too !!
Thanks :)

**Comment by ananyaarun** [comment]
Also I still feel it would be better to think about switching frameworks,
Jasmine still gives a lot of time loading problems and We have so far been writing very basic tests.

**Comment by jywarren** [comment]
Want to merge this though? Looks good! 🙌🏽

**Comment by ananyaarun** [comment]
> This looks good but perhaps we should use a common html fixture and change just the JavaScript to do the tests in a more space efficient way? And the single line constructor may help minimize the js code necessary to start layers up, no?

Yes this is exactly what I was thinking. There is too much redundant code being added because of this.
One possible way I figured is, we can use standardized js files in the fixture file. This would reduce some redundancy.

**Comment by ananyaarun** [comment]
> Want to merge this though? Looks good! 🙌🏽

Yes sure !! Would be good to have a few basic tests which at least validate if a layer is loaded at all or not :)

**Comment by jywarren** [comment]
Ok awesome that sounds great.

**Comment by sagarpreet-chadha** [comment]
AWESOME :)

**Pull request merged**
