### PR TITLE
Plpeople popups

### LINKED ISSUE #421: Format marker popups for PLpeople
In LBLD I added a new functionality to have custom code for marker popups: https://github.com/publiclab/leaflet-blurred-location-display/pull/96

Here in LEL I want to use that functionality to customize the marker popups for PLpeople, to look more in line with the content popups in plots2.

### PR DESCRIPTION
**Pull request by jywarren**
Building on and replacing #422

Citing that PR by @nstjean --

Fixes #421  (<=== Add issue number here)

**This depends entirely on https://github.com/publiclab/leaflet-blurred-location-display/pull/96 and cannot be merged until that PR is merged and published in LBLD.**

The "Joined [time ago]" depends on new data added to the API in plots2: https://github.com/publiclab/plots2/pull/7562

This is what the new popups look like:

FireShot Capture 321 - Leaflet Environmental Layers -

### CODE REVIEW

**Comment by jywarren** [comment]
Aha! This is now the same error as in #452 and #451 -- gah! So, waiting on that.

**Comment by nstjean** [comment]
Ahh, I'm sorry! Looks like you got it working, and @crisner got the text failure to work with another mock. :tada:

**Comment by jywarren** [comment]
Ah, so awesome! OK, just rebased!!!

**Comment by jywarren** [comment]
Thanks @nstjean no problem!!!

**Comment by jywarren** [comment]
DONE! Yay!!! 🎉

**Comment by jywarren** [comment]
And published `v2.4.0` !! Thank you @nstjean and @crisner !!

**Pull request merged**
