### PR TITLE
Layer control button modified

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
Showing way to tell people about Layers button  #62  .

screenshot 2018-12-06 at 10 36 41 am

screenshot 2018-12-06 at 1 11 32 am

### CODE REVIEW

**Comment by kevinzluo** [comment]
This looks cool!

Do you think there might be a way for us to even change the icon? We could make it have something to do with Publiclab!

**Comment by sagarpreet-chadha** [comment]
Yes most probably , we can overwrite the url of the icon using css .
What do you have in mind ? Thanks 😄 !

**Comment by kevinzluo** [comment]
I am actually not sure myself 😅. Maybe something like this? 
image

LEL for ℒeaflet Environmental Layers?

Though what we actually pick should be better than what I made in 5 minutes 😄 .

**Comment by sagarpreet-chadha** [comment]
@kevinzluo ...that is very cool idea . I am merging this for now and opening a new issue for the same . Thanks 😄 !

**Pull request merged**
