### PR TITLE
Add form for new spreadsheet layer to gh-pages

### PR DESCRIPTION
**Pull request by daemon1024**
Fixes https://github.com/publiclab/leaflet-environmental-layers/pull/549#issuecomment-896243225

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by daemon1024** [comment]
Here's a preview of this branch https://daemon1024.github.io/leaflet-environmental-layers/example. Seems to be working fine on my end.

**Comment by jywarren** [comment]
OK! Here, i think we could go in using GitPod (or work locally) and force re-add the fortawesome stuff to resolve the conflict. That is, you could just copy in a fresh copy of the conflicting libraries, add them and resolve the conflict in the middle of a git rebase -- make sense? 

Looks great!

**Comment by daemon1024** [comment]
There were actually 1827 conflicts :P
image

But I found out about [git merge strategies](https://git-scm.com/docs/merge-strategies#Documentation/merge-strategies.txt-ours) and chose to use the ours strategy.

**Comment by daemon1024** [comment]
The deployment seems to be working fine and there's no merge conflicts so 🥳

**Comment by jywarren** [comment]
Awesome work. Thank you!!

**Comment by jywarren** [comment]
Seeing some issues perhaps at:

https://publiclab.github.io/leaflet-environmental-layers/example/#lat=40.55&lon=-81.77&zoom=4&layers=Standard,PLpeople

image

But this works!

https://publiclab.github.io/leaflet-environmental-layers/example/form

image

New issue at: https://github.com/publiclab/leaflet-environmental-layers/issues/575

**Pull request merged**
