### PR TITLE
Test new layer browser control

### LINKED ISSUE #327: Write tests for custom layer control

### PR DESCRIPTION
**Pull request by crisner**
Fixes #327  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by crisner** [comment]
@publiclab/outreachy, @sagarpreet-chadha, @ananyaarun, @IshaGupta18,

I need help with this. I tried everything I could think of and have reached the point where I am not sure how to proceed. The following are the problems I'm having:

When running `grunt jasmine`:
```
× encountered a declaration exception
     TypeError: undefined is not a constructor (evaluating 'new L.control.layersBrowser()') in file:///D:/open-source/internship/leaflet-environmental-layers/spec/javascripts/layersBrowser.spec.js (l)

```

So upon finding many leaflet libraries using karma to run tests, I set it up to see if it helps. Here's what I have when running `karma start karma.conf.js` with PhantomJS:
```
Deprecated private createPreprocessor() API
02 01 2020 18:15:11.443:INFO [framework.browserify]: registering rebuild (autoWatch=true)
02 01 2020 18:15:12.066:WARN [filelist]: All files matched by "D:/open-source/internship/leaflet-environmental-layers/src/**/*js" were excluded or matched by prior matchers.
02 01 2020 18:15:12.067:WARN [filelist]: Pattern "D:/spec/javascripts/fixtures/*.html" does not match any file.
02 01 2020 18:15:14.126:INFO [framework.browserify]: 1034302 bytes written (0.75 seconds)
02 01 2020 18:15:14.133:INFO [framework.browserify]: bundle built
02 01 2020 18:15:14.142:WARN [karma]: No captured browser, open http://localhost:9876/
02 01 2020 18:15:14.521:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
02 01 2020 18:15:14.522:INFO [launcher]: Launching browsers PhantomJS with concurrency unlimited
02 01 2020 18:15:14.571:INFO [launcher]: Starting browser PhantomJS
02 01 2020 18:15:30.924:INFO [PhantomJS 2.1.1 (Windows 8.0.0)]: Connected on socket AU1KhFhPQBcZjhrAAAAA with id 21776413
PhantomJS 2.1.1 (Windows 8.0.0) ERROR
  An error was thrown in afterAll
  SyntaxError: Unexpected token '.'
  SyntaxError: Expected an identifier but found 'map' instead
  SyntaxError: Unexpected token '.'
PhantomJS 2.1.1 (Windows 8.0.0): Executed 0 of 0 ERROR (0.004 secs / 0 secs)
```

And here's what I have when running `karma start karma.conf.js` with Firefox:
```
Deprecated private createPreprocessor() API
02 01 2020 18:12:01.303:INFO [framework.browserify]: registering rebuild (autoWatch=true)
02 01 2020 18:12:01.486:WARN [filelist]: All files matched by "D:/open-source/internship/leaflet-environmental-layers/src/**/*js" were excluded or matched by prior matchers.
02 01 2020 18:12:01.493:WARN [filelist]: Pattern "D:/spec/javascripts/fixtures/*.html" does not match any file.
02 01 2020 18:12:03.168:INFO [framework.browserify]: 1034302 bytes written (0.90 seconds)
02 01 2020 18:12:03.176:INFO [framework.browserify]: bundle built
02 01 2020 18:12:03.183:WARN [karma]: No captured browser, open http://localhost:9876/
02 01 2020 18:12:03.236:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
02 01 2020 18:12:03.236:INFO [launcher]: Launching browsers Firefox with concurrency unlimited
02 01 2020 18:12:03.263:INFO [launcher]: Starting browser Firefox
02 01 2020 18:12:09.354:ERROR [launcher]: Cannot start Firefox

02 01 2020 18:12:09.355:ERROR [launcher]: Firefox stdout:
02 01 2020 18:12:09.355:ERROR [launcher]: Firefox stderr:
02 01 2020 18:12:12.484:INFO [launcher]: Trying to start Firefox again (1/2).
02 01 2020 18:12:12.485:WARN [temp-dir]: Failed to create a temp dir at C:\Users\chris\AppData\Local\Temp\karma-71793406
02 01 2020 18:12:18.178:ERROR [launcher]: Cannot start Firefox

02 01 2020 18:12:18.178:ERROR [launcher]: Firefox stdout:
02 01 2020 18:12:18.179:ERROR [launcher]: Firefox stderr:
02 01 2020 18:12:21.400:INFO [launcher]: Trying to start Firefox again (2/2).
02 01 2020 18:12:21.401:WARN [temp-dir]: Failed to create a temp dir at C:\Users\chris\AppData\Local\Temp\karma-71793406
02 01 2020 18:12:24.496:INFO [Firefox 71.0.0 (Windows 10.0.0)]: Connected on socket jgPd1163fTwkyjwwAAAA with id 71793406
02 01 2020 18:12:29.067:ERROR [launcher]: Firefox crashed.

02 01 2020 18:12:29.068:ERROR [launcher]: Firefox stdout:
02 01 2020 18:12:29.069:ERROR [launcher]: Firefox stderr: [Parent 4392, Gecko_IOThread] WARNING: pipe error: 109: file z:/task_1575282935/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc,
line 341
[Child 17544, Chrome_ChildThread] WARNING: pipe error: 109: file z:/task_1575282935/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 341
[Child 17544, Chrome_ChildThread
Firefox 71.0.0 (Windows 10.0.0): Executed 1 of 1 SUCCESS (0.012 secs / 0.002 secs)
TOTAL: 1 SUCCESS
02 01 2020 18:12:34.155:ERROR [launcher]: Firefox failed 2 times (crashed). Giving up.
```

So my tests are passing when using Karma and my instantiation of the control is no longer undefined but I keep getting errors related to the browsers I am using. I am also getting 404 errors when I try to use fixtures when using Karma. I am pretty new to testing and I am guessing I am not understanding something fundamental. I appreciate any help I can get on this. Thank you!

**Comment by jywarren** [comment]
Hi! Just noting I saw this and you're off to a great start. Testing can be frustrating but I'll circle back to this to see what i can suggest by end of day. Right now I'm merging PRs left and right... will catch up soon though! Thanks for your amazing work!!!

**Comment by jywarren** [comment]
First, i want to say I've struggled a lot with Jasmine myself, and I think it's just because knowing the exact state of a mocked up test environment is pretty tough. 

A lot of what you're seeing in errors seem like potentially either order-of-execution errors (like `     TypeError: undefined is not a constructor (evaluating 'new L.control.layersBrowser()') in file:///D:/open-source/internship/leaflet-environmental-layers/spec/javascripts/layersBrowser.spec.js (l)`) or similarly, timing issues, where files are loading in some order and you aren't waiting long enough for them to have completed, perhaps? 

Test environments can be so different than normal browser usage. 

Firefox seems just to be crashing, which is probably not your fault -- I might try installing another lib that uses it, where their Travis CI tests are passing using Firefox in this way, and seeing if that passes on your local machine -- it could just be Firefox itself somehow.

For the PhantomJS run, this seems key:

```
  An error was thrown in afterAll
  SyntaxError: Unexpected token '.'
  SyntaxError: Expected an identifier but found 'map' instead
  SyntaxError: Unexpected token '.'
```

Is this a line from your tests, or from the constructor, which is trying to something like `bla.map.bla`? It's really unhelpful that PhantomJS is not telling you a line number. 

One possible way to go is to set up Jasmine to run in a browser as well; you can see an example of this at http://github.com/jywarren/pxlqst (a test game I made). Then you can debug there too, as an alternative to the test env. But that may not help if your test env is what's causing the problems, as opposed to your tests themselves.

If it's at all helpful, some folks have had more success with Jest; in this PR (https://github.com/publiclab/image-sequencer/pull/1366) there's a pretty minimal clean setup for Jest that could be of interest. 

If you still have trouble with this tomorrow, I'll try downloading your code and running it, but as I said, I've struggled a good bit with Jasmine tests myself -- in fact that Image Sequencer PR was replacing one I'd been totally stuck in here: https://github.com/publiclab/image-sequencer/pull/1242

**Comment by jywarren** [comment]
@sagarpreet-chadha @nstjean if either of you are able to give these tests a try, it could be helpful! @crisner can you open separate PRs for the two ways you set this up, so each can be tried out?

**Comment by crisner** [comment]
@jywarren, thanks to your comment above I was able to figure out what was causing the phantomJS issue. Turns out the error, `SyntaxError: Unexpected token '.'` was because of es6 syntax in the files.

**Comment by crisner** [comment]
Okay, so the error `SyntaxError: Expected an identifier but found 'map' instead` is coming from the leaflet.blurred-location-display library.

**Comment by crisner** [comment]
I set up babel to transpile the layersBrowser.js file that I am testing and now my test seems to be passing when running `grunt jasmine`. I would've liked to use karma but sadly when I ran specs with fixtures it returns a bunch of 404s and fails specs that use fixtures. I cannot believe the whole ordeal was because the file had  es6 code in it. 😅 Atlast I can focus on writing tests now.

**Comment by crisner** [comment]
I'll update the pull request with the karma test runner for anyone who would like to help figuring out the fixtures issue. I'll be making another PR that uses jasmine without karma.

**Comment by sagarpreet-chadha** [comment]
Yes Jasmine doe not undertand ES6. I also learnt this the hard way :)

**Comment by crisner** [comment]
It feels better to know that I am not the only one that struggled with Jasmine. 😄 @jywarren and @sagarpreet-chadha thanks for sharing your experiences. It means a lot, and also thanks for helping out. 😄

**Comment by crisner** [comment]
Shall I close this PR as I've created another one for the same issue?

**Comment by jywarren** [comment]
Sure! and, of course! I'm so glad you figured it out, it's so satisfying!

**Comment by IshaGupta18** [comment]
So glad this worked out!

**Pull request closed without merging**
