### PR TITLE
Highlight new layers

### LINKED ISSUE #427: Highlight new layers in the layer menu
Related to issue #133. When the user checks the layer menu for the new layers it is difficult to identify them. It would be nice to add a feature as mentioned here. in https://github.com/publiclab/leaflet-environmental-layers/issues/334#issuecomment-581895937 to make it easier to find them.

### PR DESCRIPTION
**Pull request by crisner**
Fixes #427  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by crisner** [comment]
### Screenshot of the feature:
#### Index page:
image

#### Onelinercode example page:
image

**Comment by jywarren** [comment]
Just needs a rebase! Thank you!!!!

**Comment by crisner** [comment]
@jywarren and @sagarpreet-chadha, I have fixed some inconsistencies in my latest commits here. This PR is ready to be merged after the commits are reviewed. Thanks!

**Comment by crisner** [comment]
Fixed layer highlight working only on one map because of conflict in layer ids.
image

**Comment by jywarren** [comment]
Awesome work here!!!! Merging!

**Pull request merged**
