### PR TITLE
Wisconsin Non metallic layer added

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
#89 !

screenshot 2018-11-30 at 12 46 41 am
screenshot 2018-11-30 at 12 44 18 am

### CODE REVIEW

**Comment by jywarren** [comment]
AMAZING

**Comment by sagarpreet-chadha** [comment]
Merging this 😄 !

**Comment by jywarren** [comment]
amazing! ping me when it's online somewhere, the rest of the team (stevie,
liz) will be super excited!

**Comment by sagarpreet-chadha** [comment]
@jywarren  
Live here :https://publiclab.github.io/leaflet-environmental-layers/example/index.html#11/37.3590/-108.4124/BL2-FT_mobile

**Pull request merged**
