### PR TITLE
mapKnitterLayer 

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
solves #10 .

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
@jywarren ...kindly see this . 
We can change the marker - icon later . What do you think ?

screen shot 2018-06-14 at 11 58 54 am

**Comment by jywarren** [comment]
this looks amazing! Let's not worry too much about the icons -- we can
change them in follow-up as we get input from people.

Are you concerned about the load this would put on MapKnitter's API?

**Comment by sagarpreet-chadha** [comment]
I guess an average user in the worst case will make around 5 hits per second to the server and  if 50 users are using this layer simultaneously then it will add to 250 hits per second . 
I think this should not put much load on the server , but i am not sure if this is the correct way to estimate the load . What do you think ?

**Comment by jywarren** [comment]
I think that's probably right. I think it should be OK, but we'll keep an
eye out and we can do some caching to respond to this if need be. All good
then, thanks!

**Pull request merged**
