### PR TITLE
OpenInfraLayer Added

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
Solves #22 .

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
screen shot 2018-07-03 at 1 54 14 pm
screen shot 2018-07-03 at 1 55 02 pm
screen shot 2018-07-03 at 1 54 44 pm
screen shot 2018-07-03 at 1 54 30 pm

**Comment by jywarren** [comment]
Wow this is quite powerful. You could do another blog post on this!

**Comment by sagarpreet-chadha** [comment]
Great idea ! On it 👍

**Comment by sagarpreet-chadha** [comment]
Should i make one blog spot explaining OpenInfra , and Fractracker and PurpleAir as well ?

**Comment by jywarren** [comment]
sure, that's a great idea. I'm curious if there are close by feature
between Fractracker and OpenInfra, actually!

**Comment by sagarpreet-chadha** [comment]
@jywarren ...Should i merge this also ?

**Comment by jywarren** [comment]
yeah, it's great!

**Pull request merged**
