### PR TITLE
Script to generate new spreadsheet layers

### LINKED ISSUE #528: Script for generating new spreadsheet based layers
Initial Steps for #488 

Aim of the script is to generate a new spreadsheet layer based on some configuration ( json for now ).

Checklist the script should perform:

- [x] Take input from a json
- [ ] Generate `src/layername.js` with the following content
	```js
	L.layerGroup.NewLayerName = function (options) {
  			return new L.SpreadsheetLayer({
    				url: "", // String url of data sheet
    				lat: "Latitude", // name of latitude column
    				lon: "Longitude", // name of longitude column
    				columns: ["", ""], // Array of column names to be used
    				generatePopup: function () {
    						  // function used to create content of popups
    				},
    				imageOptions: {
      				icon: L.icon.mapKnitterIcon(),
    				}, // optional, defaults to blank
    				// sheetNum: // optional, defaults to 0 (first sheet)
  			});
	};
	```
- [x] Add import statement for generated file to `AllLayers.js`
- [x] Add Layer Name to `LeafletEnvironmentalLayers.js`

Ref https://github.com/publiclab/plots2/issues/9698

### PR DESCRIPTION
**Pull request by daemon1024**
Fixes #528 

TODO

- [x] Document Usage
- [ ] Handle other columns other than lat and long for more informative map layer
- [ ] use custom pop up function
- [ ] use custom marker
- [ ] Tests

### CODE REVIEW

**Comment by daemon1024** [comment]
Currently the script doesn't handle adding to AllLayers.js, I am still figuring out the architectural changes required for a better way to handle that.

**Comment by jywarren** [comment]
Looks like a great start!!! One thing is if you could include tests, they could also help demonstrate how the script is supposed to be used. And the expected output! This could also make our reviewing easier. 

Love the todo list in your PR description! Good organizing!!!

**Comment by daemon1024** [comment]
I need some guidance as to how to add tests for this script. The jasmine test suite seems to be reliant on dist/*.js for testing function. the scripts are a seperate entity though.

I have added some documentation about the script and will add further in the trailing github actions PR.

**Comment by jywarren** [comment]
OK, so we should be good to merge this once we resolve the Cypress issues, isn't that right @daemon1024 ? Thank you!

**Comment by daemon1024** [comment]
Yes, Just noticed I didn't commit the markdown file. Will do that asap. Then it's good to go.

**Comment by Tlazypanda** [comment]
Hey @daemon1024  Is this PR ready for review now? 

Also Just looping in @noi5e for guidance regarding the tests. Thank you! :v:

**Comment by daemon1024** [comment]
Yes @Tlazypanda.

Just noting that the script can be seen in action at  https://github.com/daemon1024/leaflet-environmental-layers/issues/18

Also a more complete experience at https://daemon1024.github.io/leaflet-environmental-layers/example/form.html

**Review by jywarren — APPROVED** [review]

**Comment by jywarren** [comment]
Yay! Let's not forget the other items on the checklist above!

**Pull request merged**
