### PR TITLE
Fixed OSM layer loading and checkbox problem

### LINKED ISSUE #139: OSM Landfills, Mines and Quarries checkbox not working.
@jywarren @sagarpreet-chadha The checkbox of the last layer is not ticking and thus, the layer is not being visualized.

### PR DESCRIPTION
**Pull request by ananyaarun**
Fixes #139 

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

osm

Thanks!

### CODE REVIEW

**Comment by ananyaarun** [comment]
- I have removed the requirement of minZoom = 7 for the OSM layer
- The layer now loads (checkbox works) for all zoom values. At the same time it takes way to long to load for a full map but on zoom loads quickly as shown in the gif.
- I have also added a (zoom in ) like pressure contour layer to tell users that this layers works better on zoom

**Comment by ananyaarun** [comment]
I have resolved the conflicts , do take a look @sagarpreet-chadha . Thanks !! :)

**Comment by jainaman224** [comment]
@sagarpreet-chadha I think we can add `dist/LeafletEnvironmentalLayers.js` to `.gitignore`.

**Comment by sagarpreet-chadha** [comment]
Hey Aman , great idea :smile: . We though about this and we decided to maintain dist file, like in plots2 or mapknitter we donot want to use any command to build dist file . Agreed we can make a script which can automatically make dist file after npm install LEL is executed . We can open a separate issue for this . Thanks :)

**Comment by ananyaarun** [comment]
Sure, i'll open an issue for that. Thanks!!

**Pull request merged**
