### PR TITLE
Added Indigenous Lands **Treaties** Layer. Indigenous Lands Treaties Inventory

### LINKED ISSUE #55: Make new layer using API for indigenous lands .
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

We have many layers implemented on this library , see this demo here : 
https://publiclab.github.io/leaflet-environmental-layers/example/index.html#3/43.00/-46.23

Lets add a new layer using this API : 
https://native-land.ca/api-docs/

We can take help from this merged PR [Comments have been added in this PR where changes are required] : 
https://github.com/publiclab/leaflet-environmental-layers/pull/8/files

Happy to help :)

### PR DESCRIPTION
**Pull request by kevinzluo**
Fixes #55 
3 of 3 PRs

Implemented the Indigenous Lands **Treaties** Layer

Works similar to #76, #77 .

I have decided to get data only for the specific section rather than the whole map because the territories and treaties layers are quite more complex than the languages ones. I have set clearOutsideBounds to false for now.

showingiltreatiesworkingregionalfalse

Please tell me if you would like me to change anything.

Happy to be contributing,
Kevin Luo

### CODE REVIEW

**Comment by jywarren** [comment]
I merged one and it looks awesome! But that seems to have made a conflict here. Can u resolve?

Thanks!!!

**Comment by kevinzluo** [comment]
I'll take a look as soon as I can! I am currently out of town.

**Comment by jywarren** [comment]
no rush, and thanks!

**Comment by kevinzluo** [comment]
@jywarren This one is fixed now too.

Also, should the activity in this repository be showing on Gitter? I see that most of the gitter activity feed is from plots2, but sometimes I also see other repositories, such as spectraworkbench.js, but never this one.

**Comment by jywarren** [comment]
Oh excellent. Good point on gitter... i'll check the settings!!! 👍 👍 👍

**Pull request merged**
