### PR TITLE
Add search control

### LINKED ISSUE #325: Search not open by default but behind a magnifying glass icon that pops open

### PR DESCRIPTION
**Pull request by crisner**
Fixes #325  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by crisner** [comment]
- Used search plugin from [MapBBCode](http://mapbbcode.org/leaflet.html), https://github.com/MapBBCode/mapbbcode
  - Uses search API from [OpenStreetMap Nominatim](https://nominatim.openstreetmap.org/search.php)
- Replaced icon with fontawesome icon and refactored code a bit to match default leaflet styles

#### Screenshots:
127 0 0 1_5500_example_index html (2)
127 0 0 1_5500_example_index html (3)

To do:
- Update/fine-tune input field styles

**Comment by crisner** [comment]
@sagarpreet-chadha, What do you think?

I am also planning to do the following task in the same PR.
- search for a location to re-center upon with a 🔍 button and autocomplete geocoder (like at https://github.com/publiclab/leaflet-blurred-location)

**Comment by sagarpreet-chadha** [comment]
Hey, is it possie to use their package as npm module and pass API string and parser maybe if there API allows this? Thanks!

**Comment by crisner** [comment]
I did go through their readme to see if the package could be installed as an npm module but couldn't find any. I got the code from their download option which simply lets us copy the code.

**Comment by crisner** [comment]
Should I look for another plugin that could be installed via npm?

**Comment by crisner** [comment]
I've found the perfect plugin for this. Shall update the PR after its implementation.

**Comment by crisner** [comment]
- Used [leaflet-google-places-autocomplete](https://github.com/Twista/leaflet-google-places-autocomplete) plugin for search control with places autocomplete API. Added API key from leaflet blurred location in the commit. Tested with an API key I had on an existing project.

- Deleted the file from the [previous commit](https://github.com/publiclab/leaflet-environmental-layers/pull/326/commits/5e6c15261e7a99277a887688ce40eaed61d77a39#diff-f961ce262c3c611b5a5ad5e0b07a986a)

##### Screenshot of the plugin in use:
127 0 0 1_5500_example_index html (4)
search_autocomplete

**Comment by jywarren** [comment]
oooh looking very cool!

**Comment by jywarren** [comment]
Awesome work!!!

**Comment by sagarpreet-chadha** [comment]
Perfect plugin!!! 
Most probably we hould put this in try/catch block:

`var loc = place.geometry.location;`

But that can be done later!!! Thank 😄 !

**Comment by crisner** [comment]
Sure, @sagarpreet-chadha! I'll make a note of it. Thanks!

**Comment by crisner** [comment]
@sagarpreet-chadha, a check for `place.geometry` has been used in the plugin here,

https://github.com/crisner/leaflet-google-places-autocomplete/blob/8f99306961c1045112d9d8a2fec17b25b5bc5a94/src/js/leaflet-gplaces-autocomplete.js#L97-L100

**Comment by sagarpreet-chadha** [comment]
Awesome!

**Pull request merged**
