### PR TITLE
Changed menu width of layer menu

### LINKED ISSUE #186: Increase layer menu width in layer select dropdown
## Description
The current layer menu is too small due to which some of the layer names spill to the next line making the menu crowded
Ex : Indigenous lands territories , indigenous land languages 

sizebefore

## Solution 
- Layer width can be changed to something like 250px from 200px to fit all layers in the same line.
- Shorten layer names a little like indigenous territories and indigenous languages.

### PR DESCRIPTION
**Pull request by ananyaarun**
Fixes #186 

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

lel1

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, this is nice!!! What if we also restyled the menu opening button as in page 9 of our new style guide? Thanks Ananya!!!

**Comment by ananyaarun** [comment]
Sure @jywarren , I'll look at it. Thanks !!!

**Comment by ananyaarun** [comment]
Hey @sagarpreet-chadha  I have created a new PR for the changes @jywarren asked for.
Thanks !!

**Comment by ananyaarun** [comment]
I'll solve the conflicts asap.

**Comment by ananyaarun** [comment]
@sagarpreet-chadha , I have resolved the conflicts here. Thanks !

**Comment by jywarren** [comment]
Hi! Super!! Can you share a final screenshot? Thanks!

**Comment by sagarpreet-chadha** [comment]
Hey ! Great work , 
I am going ahead and merging this 😄 !

**Comment by ananyaarun** [comment]
Hey @jywarren 
here is the screen shot. I actually made the changes you asked in a seperate PR , so this one just increases the menu width :)

lel1

**Pull request merged**
