### PR TITLE
Added mapknitter link.

### PR DESCRIPTION
**Pull request by sidntrivedi012**

### CODE REVIEW

**Comment by sidntrivedi012** [comment]
@jywarren @gauravano Please review. Fixes #129.

**Comment by jywarren** [comment]
Thank you!!!

**Comment by jywarren** [comment]
Would you like to try this one? https://github.com/publiclab/leaflet-environmental-layers/issues/153

**Comment by sidntrivedi012** [comment]
Sure @jywarren .

**Pull request merged**
