### PR TITLE
mobile fractracker layer added

### LINKED ISSUE #87: Add FracTracker mobile app data layer
FracTracker mobile app reports seem to be loaded via requests like this:

https://services.arcgis.com/jDGuO8tYggdCCnUJ/arcgis/rest/services/FracTrackerMobileAppNPCAMesaVerdeNationalPark_051416/FeatureServer/0/query?f=pbf&where=1%3D1&returnGeometry=true&spatialRel=esriSpatialRelIntersects&outFields=*&outSR=102100&resultOffset=0&resultRecordCount=8000&resultType=tile&quantizationParameters=%7B%22mode%22%3A%22edit%22%7D

Looks like arcgis FeatureLayer -- there's a plugin for them! https://esri.github.io/esri-leaflet/api-reference/layers/feature-layer.html

These are loaded under the Photo Documentation layer (2nd to last) here: http://ft.maps.arcgis.com/apps/MapJournal/index.html?appid=acb8b266e60446a2bf3fac099827c163

And are reported via the FracTracker app: https://play.google.com/store/apps/details?id=com.viableindustries.fractracker&hl=en

Response seems to be in "pbf" format... but changing `pbf` to `json` works:

https://services.arcgis.com/jDGuO8tYggdCCnUJ/arcgis/rest/services/FracTrackerMobileAppNPCAMesaVerdeNationalPark_051416/FeatureServer/0/query?f=json&where=1%3D1&returnGeometry=true&spatialRel=esriSpatialRelIntersects&outFields=*&outSR=102100&resultOffset=0&resultRecordCount=8000&resultType=tile&quantizationParameters=%7B%22mode%22%3A%22edit%22%7D

I think this should be pretty easy to add! @sagarpreet-chadha what do you think?

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
Fixes #87 !

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
Had to dig up the documentation alot 😄 !

screenshot 2018-11-29 at 11 45 02 pm

**Comment by sagarpreet-chadha** [comment]
Will open a PR in plots2 and mapknitter as soon as this gets merged . Thanks !

**Comment by jywarren** [comment]
Oh wow. This is awesome! Mind linkifying the URL so it can be clicked through? This is fantastic!

**Comment by sagarpreet-chadha** [comment]
Done 👍 !

**Comment by jywarren** [comment]
awesome! Also you can go ahead and merge things like this in, even if you give a shout out so I can see your awesome progress!

**Pull request merged**
