### PR TITLE
 PurpleAir Layer showing markers

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
Solves #14 !
💜 💨

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
New Layer : 

screen shot 2018-06-27 at 10 39 14 pm

**Comment by sagarpreet-chadha** [comment]
When using both Layers : 

screen shot 2018-06-27 at 10 39 29 pm

**Comment by sagarpreet-chadha** [comment]
@jywarren ...What do you think of this layer ?

**Comment by jywarren** [comment]
Awesome. Let's do it!

**Pull request merged**
