### PR TITLE
Changed css of LEL menu

### LINKED ISSUE #196: update style of LEL menu
The new public labs style guide specifies a certain style for the LEL menu on page 9

https://docs.google.com/presentation/d/1-XHlVn3KQxSjS5WzHgc1l1qvFwqUC5f3-7GXugUP9u4/edit?ts=5cab5403#slide=id.g573f56d3e0_1_12

The current style can be changed to fit this.

### PR DESCRIPTION
**Pull request by ananyaarun**
Fixes #196 

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

newcss

Thanks!

### CODE REVIEW

**Comment by ananyaarun** [comment]
I have made an FTO #195 to move the layer popup down as in the style guide.

**Comment by sagarpreet-chadha** [comment]
Can you give screenshot in mobile view as well ? Thanks !

**Comment by ananyaarun** [comment]
@sagarpreet-chadha  here is the Mobile view

mobile

**Comment by sagarpreet-chadha** [comment]
Awesome !!!

**Comment by jywarren** [comment]
Cool!!!

**Pull request merged**
