### PR TITLE
Fix baselayer selection in the map's layer control

### LINKED ISSUE #299: Fix active base layer selection
The active base layer appears unselected in the map's layer control.
baselayer-bug

### PR DESCRIPTION
**Pull request by crisner**
Fixes #299  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by crisner** [comment]
Screenshot of issue fixed:
baselayer-fix

**Comment by crisner** [comment]
Continuation of PR #296

**Comment by crisner** [comment]
The URL hash showed the initial base layer's name along with the active base layer's name in a map with more than one base layer when the browser was reloaded:
> http://127.0.0.1:5500/example/oneLinerCodeExample.html#lat=30.11&lon=8.92&zoom=4&layers=Grey-scale,Streets,odorreport,eonetFiresLayer

Fixed it to:
> http://127.0.0.1:5500/example/oneLinerCodeExample.html#lat=30.11&lon=8.92&zoom=4&layers=Streets,odorreport,eonetFiresLayer

**Comment by crisner** [comment]
Implemented changes in PR #296.
- removed redundant code
- moved lib folder to root

I have also pushed the changes to reflect on the gh-pages branch of my forked repo. Here are the links to the GitHub pages:

https://crisner.github.io/leaflet-environmental-layers/example/index.html#lat=43.00&lon=-45.38&zoom=3&layers=BL1

https://crisner.github.io/leaflet-environmental-layers/example/oneLinerCodeExample.html#lat=43.00&lon=-4.04&zoom=3&layers=Grey-scale

https://crisner.github.io/leaflet-environmental-layers/example/unearthing-pvd.html#lat=41.8302&lon=-71.4400&zoom=10&layers=Grey-scale

**Comment by crisner** [comment]
@sagarpreet-chadha, as you had mentioned we should change the path in the scripts for the plots file here:

https://github.com/publiclab/plots2/blob/3f239088f6028b2e87668f7cd9076295dfe4e79d/app/views/map/_mapDependencies.html.erb#L20-L21

```javascript
<%= javascript_include_tag('/lib/leaflet-environmental-layers/example/lib/glify.js') %>
```
and also add the link to the fullUrlHash.js file. I shall open an issue for this in the plots repo once this is merged. Thanks!

**Comment by sagarpreet-chadha** [comment]
Awesome thanks!

**Pull request merged**
