### PR TITLE
Tests for layer filter feature

### LINKED ISSUE #423: Write tests to check layer filtering for all layers
This is to check if all the layers in LEL are filtered correctly according to their extents in the layers menu. This would also help catch bugs if any unintentional changes are made to extents information in info.json

### PR DESCRIPTION
**Pull request by crisner**
Fixes #423  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by crisner** [comment]
I am running in to the following error for the tests I've commented out.
cyWindow
Looks like Cypress doesn't like us manipulating the hash and it breaks out of the iframe. But I can't seem to figure out why some tests pass while it triggers the error for the rest. This seems to be an ongoing issue. - https://github.com/cypress-io/cypress/issues/1244

I tried to run the tests without the hash using the test.html file using `cy.visit` but I am having issues with the DOM style attributes not being loaded. I tried a wait time of upto 15 seconds and it still gives me the same error. The same tests pass in the previous method.
cyVisit

**Comment by crisner** [comment]
Can't seem to get it to work, unfortunately. :( What do you think @sagarpreet-chadha? Do you think we should check the filtering for every single layer or just that the filtering works? If its the latter we've already done that in layerMenu.spec.js:
https://github.com/publiclab/leaflet-environmental-layers/blob/43a11e3e40ac4967dd0b1ec42cc157745b7123fa/cypress/integration/layersMenu.spec.js#L21
https://github.com/publiclab/leaflet-environmental-layers/blob/43a11e3e40ac4967dd0b1ec42cc157745b7123fa/cypress/integration/layersMenu.spec.js#L36

**Comment by jywarren** [comment]
I think it's fine to test the general functionality of the filter and not intertwine it with each individual layer. I appreciate your linking to the relevant Cypress test! Hashes are a little bit undersupported in general as a UI, so it's not super surprising. So, this should be good to go then? Thanks!!

**Comment by sagarpreet-chadha** [comment]
Yes let's not go deep into each layer file filtering. Great efforts 🙌 !!!

**Comment by crisner** [comment]
Great! The general functionality for layer filtering has already been tested in the layersMenu spec. We could close this PR since it has already been done. The only difference is in the spec included in this PR I am not only checking the layer count but also the layers individually.

**Comment by crisner** [comment]
These tests would fail because of the recent changes if we merge with master. I'll push the fix in case we decide to keep it.

**Comment by crisner** [comment]
Sorry about that. These tests will have errors only when PR #428 merged. I guess I am a bit disoriented seeing how much I confused myself over this. 😅

**Comment by jywarren** [comment]
OK, awesome!!!

**Pull request merged**
