### PR TITLE
add owmloading.gif file

### PR DESCRIPTION
**Pull request by Tlazypanda**
Fixes https://github.com/publiclab/plots2/issues/5095  

Added owmloading gif file and changed the path of referencing the file.

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by Tlazypanda** [comment]
@jywarren can you kindly review? Thanks :v:

**Comment by jywarren** [comment]
Trying to retrigger tests here! If they fail again, would you mind quoting out the error into the comments and we can troubleshoot? Thank you!!!!

**Comment by Tlazypanda** [comment]
Hey @jywarren here are the failed results - 
  CypressError: Timed out retrying: Expected to find element: '', but never found it. Queried from element: <div.leaflet-pane.leaflet-marker-pane>
CypressError: Timed out retrying: Expected to find element: '.leaflet-marker-pane img', but never found it.

I don't think they are related to this but I am not sure :sweat_smile:

**Comment by jywarren** [comment]
I think you're correct. Note it seems related to Skytruth:

```
  2 failing
  1) Skytruth layer adds markers on click:
```

Can you check the blame on the skytruth test itself? Maybe it's relying on the wrong or out of date SkyTruth API? #336 #384  also show some skytruth-related view changes, maybe we broke something back then?

Thank you @Tlazypanda ! Great investigating!!!

**Comment by jywarren** [comment]
https://github.com/buche/leaflet-openweathermap/blob/master/example/leaflet/owmloading.gif

**Comment by jywarren** [comment]
These errors were due to Skytruth, and since we're still on Skytruth's orig and old API i think we may need to turn off the tests for that until we can update it to v2 API -- will try to find a reference:

```

  2 failing
  1) Skytruth layer adds markers on click:
     CypressError: Timed out retrying: Expected to find element: '', but never found it. Queried from element: <div.leaflet-pane.leaflet-marker-pane>
      at Object.cypressErr (http://localhost:8080/__cypress/runner/cypress_runner.js:102176:11)
      at Object.throwErr (http://localhost:8080/__cypress/runner/cypress_runner.js:102128:18)
      at Object.throwErrByPath (http://localhost:8080/__cypress/runner/cypress_runner.js:102163:17)
      at retry (http://localhost:8080/__cypress/runner/cypress_runner.js:92756:16)
      at onFailFn (http://localhost:8080/__cypress/runner/cypress_runner.js:80982:16)
      at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:136088:23)
      at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:134024:31)
      at Promise._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:134081:18)
      at Promise._settlePromise0 (http://localhost:8080/__cypress/runner/cypress_runner.js:134126:10)
      at Promise._settlePromises (http://localhost:8080/__cypress/runner/cypress_runner.js:134201:18)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://localhost:8080/__cypress/runner/cypress_runner.js:130813:16)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:130823:10)
      at Async.drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:130697:14)
  2) Skytruth layer has default markers in default mode:
     CypressError: Timed out retrying: Expected to find element: '.leaflet-marker-pane img', but never found it.
      at Object.cypressErr (http://localhost:8080/__cypress/runner/cypress_runner.js:102176:11)
      at Object.throwErr (http://localhost:8080/__cypress/runner/cypress_runner.js:102128:18)
      at Object.throwErrByPath (http://localhost:8080/__cypress/runner/cypress_runner.js:102163:17)
      at retry (http://localhost:8080/__cypress/runner/cypress_runner.js:92756:16)
      at onFailFn (http://localhost:8080/__cypress/runner/cypress_runner.js:80982:16)
      at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:136088:23)
      at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:134024:31)
      at Promise._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:134081:18)
      at Promise._settlePromise0 (http://localhost:8080/__cypress/runner/cypress_runner.js:134126:10)
      at Promise._settlePromises (http://localhost:8080/__cypress/runner/cypress_runner.js:134201:18)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://localhost:8080/__cypress/runner/cypress_runner.js:130813:16)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:130823:10)
      at Async.drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:130697:14)
```

**Comment by jywarren** [comment]
Link to Skytruth API issue: https://github.com/publiclab/leaflet-environmental-layers/issues/118

**Comment by jywarren** [comment]
But these are timeout errors so maybe we can just... lengthen timeout?

**Comment by jywarren** [comment]
Let's see how this does after #503

**Comment by jywarren** [comment]
Yes, https://alerts1.skytruth.org/json?n=100&l=29.103173641957888,-90.26628971099854,29.4625145059195,-88.44942569732667 hits a HTTPS cert error and probably errors. http://alerts1.skytruth.org/json?n=100&l=29.103173641957888,-90.26628971099854,29.4625145059195,-88.44942569732667 works but...

**Comment by jywarren** [comment]
Last one, @RuthNjeri and then we can modify your PR!

**Comment by jywarren** [comment]
Nice! Merging!

**Pull request merged**
