### PR TITLE
Declared character encoding for index.html

### LINKED ISSUE #145: Declare character encoding for the HTML document.
Opening the `example/index.html` page in firefox gives the following warning in console.

image

This might require addition of just a meta charset attribute within `head`.

### PR DESCRIPTION
**Pull request by ananyaarun**
Fixes #145 

- I have added the character encoding at the top of the index.html file.
- There is no longer an error on the console.

console

Previously console gave this error
image

### CODE REVIEW

**Comment by gauravano** [comment]
Which error @ananyaarun?

**Comment by ananyaarun** [comment]
@gauravano , I have updated the PR to include both issue number and the error console showed before.

**Comment by jywarren** [comment]
Thank you very much!!! The PR is helpful. Merging!

**Comment by jywarren** [comment]
Er, i mean the notes in the original issue are very helpful. Thanks!!!

**Pull request merged**
