### PR TITLE
Clean up code to have consistent formatting

### LINKED ISSUE #301: Make code formatting consistent across files
Presently, the code has different formatting styles. The code needs to follow the styles listed below for consistency and clarity across all files,
- two spaces for indents
- brackets in `if` statements for clarity

### PR DESCRIPTION
**Pull request by crisner**
Fixes #301  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by crisner** [comment]
Thank you for pointing it out @newbazz! It shows 26 files because it includes all layer and util js files and the ESLint config files. The clean up was done in all 22 of js files. I do not know if it is recommended to clean up all files at once though. :)

**Comment by crisner** [comment]
@sagarpreet-chadha, would like your feedback on this. Changes in this PR include setting up ESLint and cleaning up files to have consistent formatting. Thanks!

**Comment by newbazz** [comment]
@crisner the pr should be atomic, can you please have 2 separate prs for 2 issues.

**Comment by jywarren** [comment]
This is great. @crisner @sagarpreet-chadha is this good to merge? Thanks!!

**Pull request merged**
