### PR TITLE
Spinner added while fetching data .

### LINKED ISSUE #72: Show small spinner while new layers are loading
... in upper left corner of map?

This is just a UI idea because some layers are slow, so it could be useful. Alternatively we could show a spinner next to their checkboxes, and that might be easier!

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
Fixes #72 !
Show small spinner while new layers are loading .

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
GIF : 

**Spinner at the center** 😄 !

spinner_gif

**Comment by jywarren** [comment]
Beautiful. Just needs a rebase. 

Would we be able to switch this repository's master branch to be named 'main'? I've been doing this across other repos. Once we merge these two PRs would be a good time to do it, no more PRs will be open. @kevinzluo heads up about this too.

**Comment by jywarren** [comment]
Once we merge these two, let's publish to npm, as well!

**Comment by jywarren** [comment]
@sagarpreet-chadha you can go ahead and merge these two when they're rebased. I can add permissions if you need. Let's bump it by a 0.0.x version (a bugfix) and release on npm. Sound good? Awesome work everyone!

**Comment by sagarpreet-chadha** [comment]
Not able to rename the master to main ! Following these commands : 

```
git branch -m master master-old
git push remote :master         # delete master
git push remote master-old      # create master-old on remote

git checkout -b master some-ref # create a new local master
git push remote master  
```


Getting this error : 
```
To https://github.com/publiclab/leaflet-environmental-layers.git
 ! [remote rejected]   master (refusing to delete the current branch: refs/heads/master)

error: failed to push some refs to 'https://github.com/publiclab/leaflet-environmental-layers.git'
```

**Comment by sagarpreet-chadha** [comment]
Published to npm 🎈 😄 !

**Comment by jywarren** [comment]
If you'd like i can do the change now, i had to make a new branch based on
master and then change the default in github settings, rather than rename.

**Comment by sagarpreet-chadha** [comment]
Okay sure ! Thanks 👍

**Pull request merged**
