### PR TITLE
Live loading from google spreadsheet for Fractracker

### LINKED ISSUE #73: Make FracTracker layer live-loading by parsing CSV
The FracTracker layer is currently static, because we need to parse a CSV into JSON. I think we can do that in code, dynamically. 

The source is here: https://github.com/publiclab/leaflet-environmental-layers/blob/master/src/fractracker.js

This map shows the location of organizations working on oil & gas issues in the US and internationally.
http://ft.maps.arcgis.com/apps/Embed/index.html?appid=8defce10bdc64a35ae4fd3997edd2b1e

The data set of this map is here :
https://docs.google.com/spreadsheets/d/19j4AQmjWuELuzn1GIn0TFRcK42HjdHF_fsIa8jtM1yw/pub?gid=288258812&single=true&output=csv

Here is a range of CSV to JSON parsers we might use! https://www.npmjs.com/search?q=parse%20csv

Eventually we might make CSV and XML parsing a utility of the whole library, since we might anticipate having to do this kind of parsing with lots of APIs.

Here's some interesting code that is parsing XML into JSON, for reference:

http://darinacosta.com/skytruth/src/dataManager.js (http://darinacosta.com/skytruth/ live)

### PR DESCRIPTION
**Pull request by kevinzluo**
Fixes #73 .

When I first tried using the CSV links in issue, I encountered CORS errors.

So, after digging around, I managed to find this website that explained how to get data from a published spreadsheet - and its even in JSON. It turns out there is a Spreadsheet API that allows for this. 

Afterwards, I just rewrote some methods and refactored some code.

fractrackerlive

### CODE REVIEW

**Comment by kevinzluo** [comment]
The incorrect capitalization is a result of a typo in the spreadsheet; there are many of these, and I also couldn't really find a way to standardize the display in the popup since much of the data was empty.

**Comment by SidharthBansal** [comment]
@sagarpreet-chadha @jywarren can you please review it.

**Comment by jywarren** [comment]
This is wonderful. I'm curious - maybe we should work on a generic "map from spreadsheet" utility class or set of functions so that we can provide a link to a Google sheet and specify the column names to use for different parameters, and this could make use of the generic code. 

Would you want to create an issue and take this on as a follow-up? We could create a GCI task for it, that'd be a really neat project!

**Comment by kevinzluo** [comment]
Yeah! I'd love to give that a shot.

**Comment by jywarren** [comment]
Awesome, maybe start by opening an issue called "abstract google spreadsheet code" and let's look at what portions of the code could be re-usable. For example, maybe a function could accept the Google Spreadsheet URL as a parameter, and output some of the necessary components for the layer. Or perhaps it could output an entire layer, and then the file for this particular layer would just call that function. The function could live in, say, `/src/util/googleSpreadsheetLayer.js` ? You can copy this text as guidance into the issue if you like and then I or someone else can make a GCI task for it. Thanks!

**Pull request merged**
