### PR TITLE
Final standardization for remaining LEL layers 

### LINKED ISSUE #198: Standardize Layer code in the LEL repository
# Description
LEL is a growing library with a set of layers. Currently the process of adding new layers is not easily described and repo contains redundant code for different layers.

# What can be done
- find similarities in code btw layers
- remove redundant code and pass layer type as parameter to a standard layer display code
(common function which could be used to reduce redundant code in layers)
- refactoring based on common functions

### PR DESCRIPTION
**Pull request by ananyaarun**
Fixes #198 

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by ananyaarun** [comment]
Progress so far -

sofar

working on standardizing the remaining 3 layers

**Comment by jywarren** [comment]
Awesomeeeee!!!!!!! Will this standardization also allow us to run some
basic standardized tests on all layers that use this system?

Thanks!!!

**Comment by ananyaarun** [comment]
@jywarren Yes !! 
I think the testing methods will be the same though. As in this standardization won't affect it.
This standardization just simplified code across LEL layers and now we have one file layercode.js instead of say 10.

**Comment by sagarpreet-chadha** [comment]
Great work @ananyaarun !!!

**Comment by ananyaarun** [comment]
Hey @sagarpreet-chadha , review this whenever you have time :)
There are a few more layers now in the src directory but I feel these layers have a reasonably different layer code and it is better to leave them as of now.

Here is a screenshot of a working map with all the standardized layers

final

**Comment by ananyaarun** [comment]
There are 2-3 layers with similar layer code eg Toxic release layer etc
But to standardize these I need to include a different request data function (it uses a different way)

We can do this in the same file or make a separate file for them 
which do you think we can do ?

Thanks!!

**Comment by jywarren** [comment]
This is super. Yes, we can also do this iteratively! Let's merge!

**Comment by ananyaarun** [comment]
Thanks for the review @jywarren :)
 @sagarpreet-chadha I think this can be merged now !

**Comment by sagarpreet-chadha** [comment]
Awesome :)

**Pull request merged**
