### PR TITLE
mapknitter size changed

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
Smaller red markers .

screen shot 2018-07-30 at 9 19 19 pm

### CODE REVIEW

**Comment by jywarren** [comment]
Hmm, could we do half height AND half width, so they preserve the same aspect ratio? Otherwise, this looks SUPER! 🎉

**Comment by sagarpreet-chadha** [comment]
Done 👍 .
Thanks !

**Comment by sagarpreet-chadha** [comment]
screen shot 2018-07-30 at 9 43 08 pm

**Comment by sagarpreet-chadha** [comment]
Hi @jywarren !
Kindly review this one also .

**Comment by jywarren** [comment]
Perfect! Merge when you're ready? 👍 👍 👍

**Comment by jywarren** [comment]
And if you want to do a minor version 0.0.x release, i can pull it into MapKnitter and restart it :-)

**Comment by sagarpreet-chadha** [comment]
Yes lets do it .
Do i have to change this line to `1.0.1` ? 
https://github.com/publiclab/leaflet-environmental-layers/blob/94015d0804c27aca8765b9d62200f75857f58760/package.json#L3

Thanks !

**Comment by jywarren** [comment]
yes, that's right!

**Pull request merged**
