### PR TITLE
Positioned layer menu popup to bottom right

### LINKED ISSUE #195: Move Layer menu popup to bottom right corner
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [index.html](https://github.com/publiclab/leaflet-environmental-layers/blob/master/example/index.html) in the `LEL` repository to remove line 287
`var leafletControl = new L.control.layers(baseMaps,overlayMaps);`
and add this instead of that line
`var leafletControl = new L.control.layers(baseMaps,overlayMaps,{position: 'bottomright'});`

This makes the style of LEL follow the style guide of Public Lab , as given on page 9.
https://docs.google.com/presentation/d/1-XHlVn3KQxSjS5WzHgc1l1qvFwqUC5f3-7GXugUP9u4/edit?ts=5cab5403#slide=id.g573f56d3e0_1_12

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by AnkitMishra17**
Fixes #195 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by AnkitMishra17** [comment]
@ananyaarun kindly look into it.

**Comment by AnkitMishra17** [comment]
@ananyaarun is it ok now?

**Comment by ananyaarun** [comment]
Looks good to me :)

**Comment by ananyaarun** [comment]
Hey at @AnkitMishra17 can u also add a screenshot of the changes so that @sagarpreet-chadha can review it ?

**Comment by AnkitMishra17** [comment]
Hey @ananyaarun, what exactly do I have to add a screenshot of? I don't see any difference when I open index.html, just zoom-in and zoom-out buttons along with the map.

**Comment by ananyaarun** [comment]
Oh really ?!  isn't the layer menu visible ? Did u clone the latest version of the repo and run npm install before opening index.html ?

**Comment by AnkitMishra17** [comment]
Yes, I did.

**Comment by jainaman224** [comment]
@AnkitMishra17 I think you have deleted `package-lock.json` in your commit by mistake. It was meant to be removed from your commit.

I think you can run
`git checkout master -- package-lock.json`.

**Comment by ananyaarun** [comment]
@AnkitMishra17 , I just cloned the repo to test (present latest version ) and ran npm install.
I am able to see all layers and the menu.
There was a recent PR merged to solve this. Can u pls pull the changes again and test ?
If it still doesn't work add a screenshot of your console, We can help you fix the error :smiley: 
Thanks !!

**Pull request closed without merging**
