### PR TITLE
Common requring and More base layers also added [Resolves #5]

### LINKED ISSUE #5: Move requiring of common libraries to leafletEnvironmentalLayers.js
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/questions/_comment.html.erb](https://github.com/publiclab/plots2/blob/b56de9d1591c05f0cc35de95c1d7685938b4ec12/app/views/questions/_comment.html.erb#L28) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) with lines to remove in file (Remember to be careful with the indentation):  https://github.com/publiclab/leaflet-environmental-layers/blob/gh-pages/src/skyTruthLayer.js

```diff
- require('jquery') ; 
- require('leaflet') ; 

L.Icon.SkyTruthIcon = L.Icon.extend({
    options: {
      iconUrl: 'https://www.clker.com/cliparts/T/G/b/7/r/A/red-dot.svg',
      iconSize:     [30, 20], 
      iconAnchor:   [20 , 0], 
      popupAnchor:  [-5, -5] 
    }
});
```
and the lines to add in file : https://github.com/publiclab/leaflet-environmental-layers/blob/gh-pages/src/leafletEnvironmentalLayers.js

```diff
- /* comment */
- // require('leaflet') ; 
+ require('jquery') ; 
+ require('leaflet') ; 
require('./skyTruthLayer.js') ; 
```

- [ ]  **Run** command - **grunt build**  in terminal . 

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
Resolves #5 !

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
@jywarren 
I have changed Base Layers in this PR , as the previous layers were loading slowly . [Total 4 layers now , 2 new added 😄 ] .

screen shot 2018-06-27 at 11 26 25 pm
screen shot 2018-06-27 at 11 26 09 pm

**Comment by sagarpreet-chadha** [comment]
What do you think ? Should i merge this ?

**Comment by jywarren** [comment]
Sure! Very nice! Maybe we can put the base layers at the bottom of the
layers list, though? I like the grey one because it is not so noisy... but
if it's slow, the blue oceans one is nice as a defaul.

**Comment by sagarpreet-chadha** [comment]
Thanks @jywarren !!!
Merging this then and opening a new issue to put Base Layers option at bottom of the list .

**Comment by jywarren** [comment]
👍🏼

**Pull request merged**
