### PR TITLE
separate html and css

### LINKED ISSUE #213: Separate html and css code in index.html file
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [index.html](https://github.com/publiclab/leaflet-environmental-layers/blob/master/example/index.html) in the `LEL` repository to separate the html and css code present in it.

Move line 39 to 74 to a new file called style.css.
After this index.html will contain no css code and use this to link the newly created stylesheet in index.html
` <link rel="stylesheet" href="styles.css"> `
place style.css in example directory

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by subhamskm**
Fixes #213

- [✔️] PR is descriptively titled 📑 and links the original issue above [🔗]
- [✔️] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
- [✔️] code is in a uniquely-named feature branch and has no merge conflicts 📁
- [✔️] screenshots/GIFs are attached 📎 in case of UI updation
- [✔️] ask @publiclab/reviewers for help, in a comment below

### CODE REVIEW

**Comment by subhamskm** [comment]
> @subhamskm Good job 🎉
> Can you pls follow the PR template and add a screenshot of the working layers after the changes ?
> Thanks!!

Do you mean the screenshot of index.html and styles.css?

**Comment by ananyaarun** [comment]
@subhamskm , a screenshot like this

pic

first run npm install to install the dependencies then
you can open index.html in your browser.
Thanks !!

**Comment by subhamskm** [comment]
I think the leaflet control is not working..
Screenshot from 2019-06-25 21-04-09

**Comment by ananyaarun** [comment]
did u run npm install ?
looks like all dependencies are not installed.

**Comment by subhamskm** [comment]
Yes I did 'npm install'. It was giving the same error on Windows also.

**Comment by ananyaarun** [comment]
Hey, I locally cloned your branch and ran it, it works fine for me and the changes you have made are correct :)
check your dependencies again or proxy settings, I am not actually sure why it is not working.
Also can u add a screenshot of the error you get in your console ?

**Comment by subhamskm** [comment]
Screenshot from 2019-06-25 21-04-09
Here it is. It has some unmet peer dependencies. I tried to install them individually but that didn't solve the problem.

**Comment by ananyaarun** [comment]
I think you can ignore the individual unmet peer dependencies.
It works fine without them.
What error do you see on your console ? not terminal.

**Comment by subhamskm** [comment]
Screenshot from 2019-06-25 22-12-27
LeafletEnvironmentalLayers.js is not present in the dist folder.

**Comment by subhamskm** [comment]
OK.. I ran 'grunt build'. Now everything is working fine. I think the PR can be merged.
Screenshot from 2019-06-25 22-52-16

**Comment by ananyaarun** [comment]
Sure, Thanks a lot!!!
We are actually having a discussion regarding the dist folder and adding it to gitignore so that newcomers don't face issues during building the repo.

**Comment by ananyaarun** [comment]
@sagarpreet-chadha kindly merge this PR, This separates css and html code.

**Pull request merged**
