### PR TITLE
change colors in layer selection menu.

### LINKED ISSUE #9: Change the colors or add images of marker in layer selection menu .
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

We have a demo map here : 
https://publiclab.github.io/leaflet-environmental-layers/example/mapSimple.html

# Problem : 
On the right most corner , you will find a button with options to choose different layers . However if one selects more than a layer at a time then there might be ambiguity that **which marker belongs to which layer .**
screen shot 2018-06-05 at 2 45 48 pm

# Solution : 
1.) Lets add color to layer-name in the menu : 
Example : 
https://github.com/publiclab/leaflet-environmental-layers/blob/b5fd8fdbf388e059686ec5e962d89f382a4d85e6/example/mapSimple.html#L69
can be changed to : 
`"<span style='color: red'>SkyTruth</strong>": SkyTruth , `
#### output : 
screen shot 2018-06-05 at 2 41 35 pm

2.) Or we add the marker itself along with the layer name like this : 
` "SkyTruth": SkyTruth , `
#### output : 
screen shot 2018-06-05 at 2 41 12 pm

*  **You can use combination of above 2 solutions for all layers .**

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

### PR DESCRIPTION
**Pull request by Rishabh570**
Fixes #9.

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
Hi @Rishabh570 ...can you share a screenshot showing the changes ? Thanks !

**Comment by Rishabh570** [comment]
/home/rishabh570/Pictures/Screenshot from 2018-10-02 23-06-12.png

**Comment by Rishabh570** [comment]
screenshot from 2018-10-02 23-06-12

**Comment by Rishabh570** [comment]
@sagarpreet-chadha sorry for delay :)

**Comment by sagarpreet-chadha** [comment]
This is really cool @Rishabh570 !!!

Can you do 1 change of adding markers icon (as you have done for Fractracker and OdorReport) for PurpleAir-Markers , SkyTruth , ToxicRelease , OdorReport , Mapknitter AND removing text color for these as well . 

You can find the link to image/icon url in the respective JS file : 
https://github.com/publiclab/leaflet-environmental-layers/tree/master/src

Thank you so much 😄 !

**Comment by Rishabh570** [comment]
screenshot from 2018-10-03 11-45-17

**Comment by Rishabh570** [comment]
@sagarpreet-chadha Updated :)

**Comment by sagarpreet-chadha** [comment]
@Rishabh570 

If you are interested , would like to document the hexadecimal color value and corresponding layer name in an ordered tabular form in Readme.MD .

PS: I think we can use that table to extend the Leaflet-hash library BUT that is much later issue :)

**Comment by Rishabh570** [comment]
@sagarpreet-chadha Sure, I'll do it!

**Comment by jywarren** [comment]
Awesome!!!!! 🎉

**Pull request merged**
