### PR TITLE
prevent jQuery from being loaded multiple times

### LINKED ISSUE #95: Bug: Jquery script being loaded multiple times.
I was testing out the maps and saw this occur:

jquerymultipleloads

I am not too sure about its effect on performance, but I think we could just add `<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>` to index.html and then edit the use of the script in each layer.

I believe lines like this are the culprit. Every layer has them and I suggest we remove them.

https://github.com/publiclab/leaflet-environmental-layers/blob/db25167538da307a5cc2b2ad279ba347a0dda17b/src/toxicReleaseLayer.js#L51-L53

https://github.com/publiclab/leaflet-environmental-layers/blob/db25167538da307a5cc2b2ad279ba347a0dda17b/src/toxicReleaseLayer.js#L65

### PR DESCRIPTION
**Pull request by rkpattnaik780**
The lines of code that appended jQuery to the head tag have been re-written to check if jQuery has been added before appending it to the head.

fixes #95

### CODE REVIEW

**Comment by jywarren** [comment]
Oh this is nice, thank you -- do you think we could standardize these into a single function like `checkJquery()` so that there is less code redundancy? Thank you!!!!

**Comment by rkpattnaik780** [comment]
> Oh this is nice, thank you -- do you think we could standardize these into a single function like `checkJquery()` so that there is less code redundancy? Thank you!!!!

Yeah i think that will be nice. Do you think it will be better we put that method in a file in `src/util` and then call the function in other files as and when needed, to make it modular?

**Comment by gauravano** [comment]
@jywarren

**Comment by jywarren** [comment]
That sounds perfect. Thank you!!!

**Comment by rkpattnaik780** [comment]
@jywarren the latest commit seems to have introduced a bug, some of the layers, including the fractrack layer do not work. And I see the fractrack layer doesn't append multiple jQuery files even in the older versions.

**Comment by rkpattnaik780** [comment]
@jywarren @sagarpreet-chadha @gauravano . I have updated the PR based on [this](https://github.com/publiclab/leaflet-environmental-layers/issues/95#issuecomment-471252880). All the layers to which I made this change are working properly. Please test it again to check if I have missed any edge case. 

I couldn't test the following layers and hence did not implement the changes in them :- 

- OSMLandfillMineQuarryLayer : Seems this layer is somehow not working in the html file. An issue has already been opened regarding it( #139 ).
- SpreadSheetLayer : No checkbox in HTML file to test this layer.
- ToxicReleaseLayer : It did not work in my system. I think we have a possible issue there, I would open the issue soon. 

Thank you :)

**Comment by jywarren** [comment]
Oh this is wonderful. I'm sorry it took me a while to catch up. Very much appreciated!!!

**Comment by jywarren** [comment]
I'm going to bump the version number so this gets released across other platforms like https://github.com/publiclab/plots2/ -- thank you!!!

**Pull request merged**
