### PR TITLE
Add tests for Eonet Fires Layer

### LINKED ISSUE #405: Write tests for EONET fires layer
We do not have tests for many layers. Starting with writing tests for Eonet fires layer.

### PR DESCRIPTION
**Pull request by crisner**
Fixes #405  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by crisner** [comment]
@sagarpreet-chadha, @nstjean I have added tests for the Eonet fires layer in this PR. We can use the specs here to add the tests for other layers. Please let me know if I have missed writing tests for any use cases you feel would be a good to add to the spec. Thanks! 😄

**Comment by crisner** [comment]
Noting it here: The tests will most likely fail when PR #385 is merged as the layer id will be different. Fixing the layer id in the specs to match the change would fix it.

**Comment by nstjean** [comment]
Yay!!! So exciting to see!

One think I'm not sure about - should we be including the json info in the test itself? My worry is that the json in the live site gets messed up and the test doesn't pick it up because it's using its own, separate data. Or is this just mocking the response that the layer provides?

**Comment by crisner** [comment]
It is just mocking the response from the API to make sure our layers are working as it should. It wouldn't pick up any changes in the response from the actual API. We could write seperate tests for it but should we be testing someone else's API? It makes sense to test the popup information this way but we may have several other issues such as a change in CORS or an issue with their server. We also have the response time to worry about.

**Comment by nstjean** [comment]
Yes, you are right. I think mocking the API is the best option for these tests.

**Pull request merged**
