### PR TITLE
Display directions on top of map

### LINKED ISSUE #308: Display directions on top of map in the demo page
Created issue from https://github.com/publiclab/leaflet-environmental-layers/pull/296#issuecomment-564094149

### PR DESCRIPTION
**Pull request by crisner**
Fixes #308  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by crisner** [comment]
Added directions on top of the demo page.
##### Screenshot of the feature:
127 0 0 1_5500_example_index html (3)

##### Screenshot from smaller devices

**Comment by crisner** [comment]
@jywarren, could you take a look at this to see if this is what you had in mind?

**Comment by jywarren** [comment]
Awesome! This looks great. But, it would only appear on some pages, is that right? Like, this won't affect the main demo page at https://publiclab.github.io/leaflet-environmental-layers/example/ or its usage in `plots2`? Just making sure!

Shall we add a link to the embed generator demo from the README now? Thanks!

**Comment by crisner** [comment]
@jywarren, in this PR it is implemented on the /leaflet-environmental-layers/example/index.html page and will not appear anywhere else. To add them to a page we will need to add,

```
var displayInfo = new L.control.info({
  text: 'Pan & zoom the map below and select layers to display, then use the `</>` button to generate an embed code you can use on your own website.'
});
displayInfo.addTo(map);
```

So, for now, this will appear only on the https://publiclab.github.io/leaflet-environmental-layers/example/index.html.

**Comment by sagarpreet-chadha** [comment]
Super cool!!!
Lets document this also in readme.md :)

**Comment by jywarren** [comment]
Great. I do wonder if we should clone it into an `embed.html` file, or make it contingent on a URL param, so that people can, if they want, directly embed our gh-pages demo on other sites? Not a huge thing, but it could be really convenient not to necessarily need it to drive out of `plots2`. What do you think?

**Comment by crisner** [comment]
I am not sure I understand. Do you mean somehow add the directions property on the page URL? Or just clone the entire index.html page to embed.html?

**Comment by sagarpreet-chadha** [comment]
Yes agreed.

**Comment by jywarren** [comment]
I think just cloning it is probably easiest, yes! Then it'd show up at a
slightly different URL, and the URL of the actual embeds wouldn't end up
showing that notice. Make sense?

**Comment by crisner** [comment]
Yes, agreed.

**Pull request merged**
