### PR TITLE
version 2.2.0 and bump LBL to 1.7.0

### PR DESCRIPTION
**Pull request by nstjean**
Bumping version to 2.2.0
and leaflet-blurred-location to 1.7.0
so that the recent changes will work on plots2

### CODE REVIEW

**Comment by jywarren** [comment]
Awesome.

**Comment by crisner** [comment]
@jywarren and @nstjean, just a heads up. When bumping LEL version to 2.2.0 on plots2 we will need to add the following option to the LEL instantiations in [setupInlineLEL](https://github.com/publiclab/plots2/blob/d0b6db8d7536198e7ab417fb705a15fbbff3bc30/app/assets/javascripts/leaflet_helper.js#L105-L107) and [setupLEL](https://github.com/publiclab/plots2/blob/d0b6db8d7536198e7ab417fb705a15fbbff3bc30/app/assets/javascripts/leaflet_helper.js#L141-L143) functions in [leaflet_helper.js](https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/leaflet_helper.js) for the layers to be displayed on the map by default.
https://github.com/publiclab/leaflet-environmental-layers/blob/4109b587196fbe35b2adfc24ce9503e206d54bee/example/unearthing-pvd.html#L84

**Comment by nstjean** [comment]
Ok perfect. I'll get that added when I bump it in plots2!

**Comment by nstjean** [comment]
@jywarren Is this published to npm?

**Pull request merged**
